FlipsideCrypto/solana-models

- .gitignore
- README.md
- dbt_project.yml
- macros/create_sps.sql
- macros/create_tasks.sql
- macros/custom_naming_macros.sql
- macros/sp_create_prod_clone.sql
- macros/task_run_sp_create_prod_clone.sql
- models/bronze/bronze_solana__blocks.sql
- models/bronze/bronze_solana__transactions.sql
- models/sources.yml
- packages.yml
- Initial setup to run Solana Models as its own project
- Models will be built in `SOLANA` database
- Dev clone will be auto created nightly as `SOLANA_DEV`
> An 810/initial setup

- README.md
- add note about block_id vs. slot
> update readme with notes regarding solana block

- macros/tests/null_threshold.sql
- models/silver/silver__transactions.sql
- models/silver/silver__transactions.yml
- models/silver/silver__votes.sql
- models/silver/silver__votes.yml
- cast fields to appropriate data types
- fix json parsing for `vote_hash` and `vote_slots`
> fix data types

- models/silver/silver__votes_agg_block.sql
- models/silver/silver__votes_agg_block.yml
- Create table for vote counts aggregated by block
> An 841/votes block agg

- models/silver/silver__transactions.sql
- models/silver/silver__votes.sql
- Need to use `IS_NULL_VALUE` function to check for null values within json object.  Using `IS NULL` check does not work.
> fix succeeded value

- models/descriptions/event_type.md
- models/descriptions/inner_instruction.md
- models/descriptions/instruction.md
- models/descriptions/program_id.md
- models/descriptions/tx_succeeded.md
- models/silver/silver__events.sql
- models/silver/silver__events.yml
- models/silver/silver__staking_lp_actions.sql
- models/silver/silver__staking_lp_actions.yml
- models/silver/silver__transactions.yml
- Add tests for `staking_lp_actions`
- Add more common description files
- Fix `staking_lp_actions` unique key
- Minor description issues in various tables
> An 837/create lp actions

- models/silver/silver__transactions.sql
- Put in explicit order when putting the signers back into array format
> maintain order when re-aggregating into array

- models/silver/silver__votes_agg_block.sql
- fix unique key value for `votes_agg_block`
> remove tx_id from unique key

- models/silver/silver___post_token_balances.sql
- models/silver/silver___pre_token_balances.sql
- Add the account address that the index maps to
> get account address using the index

- models/silver/silver__swaps_jupiter_dex.sql
- models/silver/silver__swaps_jupiter_dex.yml
> An 842/create jupiter swaps

- models/descriptions/amount.md
- models/descriptions/index.md
- models/descriptions/tx_from.md
- models/descriptions/tx_to.md
- models/silver/silver__transfers.sql
- models/silver/silver__transfers.yml
> An 836/create transfers

- models/silver/silver__swaps_jupiter_dex.sql
- models/silver/silver__swaps_orca_dex.sql
- models/silver/silver__swaps_orca_dex.yml
> An 843/create orca swaps

- models/core/core__fact_swaps.sql
- models/core/core__fact_swaps.yml
- core swaps view.  using to test comments flow using v1.0 dbt cloud
> core swaps

- models/silver/silver__nft_metadata.sql
- models/silver/silver__nft_metadata.yml
- models/sources.yml
> add nft metadata model

- macros/task_run_sp_create_prod_clone.sql
- pushing this to later in the day because the incremental job doesnt even start until 7am UTC
> change dev refresh time

- models/silver/silver__transactions.sql
- Need to get the signers after the qualify statement otherwise uncle blocks or re-processed records will create more signers than actual
> add signers after qualify stmt

- models/silver/silver__saber_gauges_votes.sql
- models/silver/silver__saber_gauges_votes.yml
- models/silver/silver__saber_gov_actions.sql
- models/silver/silver__saber_gov_actions.yml
- Create data model for saber gauges voting
- Create data model for saber governance actions (lock/exit)
> An 892/create saber gauges and locks

- dbt_project.yml
- models/core/core__dim_labels.sql
- models/core/core__dim_labels.yml
- models/core/core__fact_events.sql
- models/core/core__fact_events.yml
- models/core/core__fact_nft_sales.sql
- models/core/core__fact_nft_sales.yml
- models/core/core__fact_staking_lp_actions.sql
- models/core/core__fact_staking_lp_actions.yml
- models/core/core__fact_swaps.sql
- models/core/core__fact_swaps.yml
- models/core/core__fact_transactions.sql
- models/core/core__fact_transactions.yml
- models/core/core__fact_transfers.sql
- models/core/core__fact_transfers.yml
- models/core/core__fact_votes_agg_block.sql
- models/core/core__fact_votes_agg_block.yml
- models/silver/silver___prices.sql
- models/silver/silver___prices.yml
- models/silver/silver__transactions.sql
- models/sources.yml
- Create core views on top of silver tables
- Add column exists checks on views.  No additional tests in this layer because all the logic is in silver.
> An 868/core views

- models/core/core__fact_swaps.sql
- models/core/core__fact_swaps.yml
- models/silver/silver__swaps_saber_dex.sql
- models/silver/silver__swaps_saber_dex.yml
- Add saber swaps model
- Add the model to core swaps
> add saber swaps model

- models/core/core__fact_nft_sales.sql
- models/silver/silver__nft_sales_opensea.sql
- models/silver/silver__nft_sales_opensea.yml
- Add Opensea Solana NFT Sales model
> An 987/opensea nft sales

- models/silver/silver__nft_mints.sql
- Add marinade NFT mints related to MNDE locks for governance
- Price for these mints will be 0 because the value is in the MNDE lock which can be increased over-time.  This MNDE value will be tracked in a separate table related to governance
> add nfts related to marindate governance

- models/silver/silver___inner_instructions.sql
- models/silver/silver___instructions.sql
- models/silver/silver___post_token_balances.sql
- models/silver/silver___pre_token_balances.sql
- models/silver/silver__blocks.sql
- models/silver/silver__events.sql
- models/silver/silver__gauges_votes_saber.sql
- models/silver/silver__gov_actions_marinade.sql
- models/silver/silver__gov_actions_marinade_tmp.sql
- models/silver/silver__gov_actions_saber.sql
- models/silver/silver__nft_mints.sql
- models/silver/silver__nft_sales_magic_eden_v1.sql
- models/silver/silver__nft_sales_magic_eden_v2.sql
- models/silver/silver__nft_sales_opensea.sql
- models/silver/silver__nft_sales_smb.sql
- models/silver/silver__nft_sales_solanart.sql
- models/silver/silver__nft_sales_solport.sql
- models/silver/silver__proposal_votes_marinade.sql
- models/silver/silver__staking_lp_actions.sql
- models/silver/silver__swaps_jupiter_dex.sql
- models/silver/silver__swaps_orca_dex.sql
- models/silver/silver__swaps_raydium_dex.sql
- models/silver/silver__swaps_saber_dex.sql
- models/silver/silver__transactions.sql
- models/silver/silver__transfers.sql
- models/silver/silver__votes.sql
- models/silver/silver__votes_agg_block.sql
- tests/silver__inner_instructions__program_id-assert-not-null.sql
- Temporarily change incremental to do 5 days worth of data.  Will revert back once we reload the data.
> temp load last 5 days on incremental

- models/silver/silver__swaps_jupiter_dex.sql
- Add another subset of lifinity token swap instructions to patch fix
> An 1409/patch jup ag swaps issues

- models/core/core__fact_gauges_creates.sql
- models/core/core__fact_gauges_creates.yml
- models/core/core__fact_gauges_votes.sql
- models/core/core__fact_gauges_votes.yml
- models/descriptions/event_index.md
- models/descriptions/gov_action_locker_nft.md
- models/descriptions/tribeca_gauge.md
- models/descriptions/tribeca_gauge_delegated_shares.md
- models/descriptions/tribeca_gauge_power.md
- models/descriptions/tribeca_gauge_validator_account.md
- models/descriptions/tribeca_gauge_voter.md
- models/descriptions/tribeca_gaugemeister.md
- models/silver/silver__decoded_instructions_data.sql
- models/silver/silver__decoded_instructions_data.yml
- models/silver/silver__events.yml
- models/silver/silver__gauges_creates_marinade.sql
- models/silver/silver__gauges_creates_marinade.yml
- models/silver/silver__gauges_votes_marinade.sql
- models/silver/silver__gauges_votes_marinade.yml
- models/silver/silver__gauges_votes_saber.yml
- Gauges governance models for Marinade
- Add standardized descriptions for tribeca gauges for use w/ marinade and saber gov
> An 1389/marinade gauges models

- macros/sp_create_prod_clone.sql
- fix issue with granting proper perms for cloned functions that have parameters
> fix issue with granting ownership for funcs with params

- models/silver/silver__nft_sales_solport.sql
- solport seller is in index 2 not 6
> seller is listed in index 2 not 6

- dbt_project.yml
- macros/create_udfs.sql
- macros/run_sp_bulk_get_validator_metadata.sql
- macros/sp_create_bulk_get_validator_metadata.sql
- macros/udf_bulk_get_validator_metadata.sql
- models/sources.yml
- add dbt macro to update bronze validator metadata table using external api call
> integrate validator metadata call

- models/silver/silver__staking_lp_actions.sql
- include nested staking events that use the solana staking program in the lp actions table
> add nested instructions that use staking program

- models/silver/silver__nft_mints.sql
- models/silver/silver__nft_mints_tmp.sql
- models/silver/silver__nft_mints_tmp.yml
- tests/silver__blocks__block_hash-assert-no-gaps.sql
- add missing mints without mint price/mint currency
> add missing mints without mint price

- dbt_project.yml
- macros/create_tasks.sql
- macros/run_sp_create_prod_clone.sql
- macros/task_run_sp_create_prod_clone.sql
- Remove dev refresh snowflake task
- Add dbt macro for calling the dev refresh stored procedure
> add macro to be called on dbt cloud

- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_historical.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_historical.sql
- macros/streamline/sp_refresh_external_table_batch.sql
- Needed to add coalesces so that the incremental loading task would work on genesis batch
> add coalesces for first batch

- models/silver/silver__nft_bids_yawww.sql
- models/silver/silver__nft_bids_yawww.yml
- models/silver/silver__nft_sales_yawww.sql
- Split bids for yawww into own model
- Reference full bids table to find the winning bid to get sales amount in the sales table
> split bids into own model then reference in sales

- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_historical.sql
- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_real_time.sql
- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_historical.sql
- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_real_time.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_historical.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_real_time.sql
- add back removed code to tasks
- temporarily add real time integration to historical tasks
> revert task changes temporarily add real time call to historical

- models/silver/silver__votes2.sql
- models/silver/silver__votes2.yml
Create Solana Votes2 model from streamline bronze data - [https://team-1612274056224.atlassian.net/browse/AN-2123](url)
- Filter all vote transactions from "bronze__transactions2"
- Reference logic from 'silver__transactions2" and original "silver__votes"
- Create yml file
Test results:
> Solana votes2

- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_historical.sql
- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_historical.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_historical.sql
- macros/streamline/run_sp_refresh_external_tables_full.sql
- macros/streamline/sp_refresh_external_tables_full.sql
- Adding a sp to refresh tables needed for some silver models so that this can be called in dbt cloud in place of existing statements
> add macros to refresh tables in streamline database

- macros/create_udfs.sql
- macros/python/udfs.sql
- models/silver/silver__events2.sql
- models/silver/silver__events2.yml
- events model from streamline data
> An 2140/events model from streamline data

- models/silver/silver__transactions2.sql
- Block time is now available from the bronze model moving forwards.  Grab from bronze and use the blocks2 table as fallback
> get block timestamp from bronze when available

- models/silver/silver__staking_lp_actions2.sql
- models/silver/silver__staking_lp_actions2.yml
- models/silver/silver__transfers2.sql
- models/silver/silver__transfers2.yml
Create lp_actions_2 and transfers_2 from streamline tables
> An 2142 lpactions and transfers from streamline data

- models/silver/silver___instructions.yml
- models/silver/silver___post_token_balances.yml
- models/silver/silver___pre_token_balances.yml
- models/silver/silver__events2.yml
- models/silver/silver__transactions.yml
- models/silver/silver__transactions2.yml
- models/silver/silver__votes2.yml
- reduce test times by looking at only recent data for certain columns
- add conditions for certain votes2 column tests
> An 2216/votes2 test failures

- models/silver/silver__transactions2.sql
- models/silver/silver__transactions2.yml
- Add version column, list of current values are `null, legacy, 0`
> add transaction version col

- models/core/core__ez_signers.sql
- models/core/core__ez_signers.yml
- Expose silver signers to core
> initial release

- models/silver/silver__transfers.sql
- add merge predicates for transfers table
> optimize incremental

- models/silver/silver__blocks.sql
- Existing incremental CTE was still causing a full scan due to how the underlying view was getting the `_inserted_timestamp`.  This solves that issue by first getting the subset of blocks we may potentially need to load by using the `_inserted_date` on it's own and then using that base cte to filter by `_inserted_timestamp`.
> update incremental to prevent full scan

- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_scheduled_incremental.yml
- profiles.yml
- workflow jobs to replace dbt cloud
> Tmp dbt replacement

- macros/create_udfs.sql
- macros/python/udfs.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.sql
Add missing udf `udf_get_jupv4_inner_programs` and remove dev reference in model
> Hot fix/add missing jupv4 udf

- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_scheduled_incremental.yml
- profiles.yml
- Update incremental workflow template to allow for synchronous multi dbt commands
- Update adhoc template to allow for environment and warehouse inputs
> standardize env var names, allow env choice, multi cmd workaround

- .github/workflows/dbt_run_dev_refresh.yml
- .github/workflows/dbt_run_weekly.yml
- migrate over dev refresh and validator metadata jobs
> schedule rest of dbt cloud jobs on github

- macros/sp_create_prod_clone.sql
- simplify the code / run fewer sql statements
> refactor db refresh code

- .github/workflows/dbt_docs_update.yml
- change docs update workflow so it doesn't break the github pages configuration
> always checkout from main, force upstream to docs

- models/silver/nfts/silver__nft_sales_magic_eden_v1.yml
- It looks like ME has fully moved off the v1 program, no txs of any kind since 14 days ago, confirmed via solscan https://solscan.io/account/MEisE1HzehtrDpAAT8PnLHjpSSkRYakotTuJRPjTpo8
> this programid not being used

- models/core/core__fact_nft_sales.sql
- models/silver/nfts/silver__nft_sales_magic_eden_v1.sql
- models/silver/nfts/silver__nft_sales_solanart.sql
- models/sources.yml
- Add `enabled=false` config to the models
- Add the existing data as sources so that the core views can continue to reference them w/o error
> disable models with no new data

- models/core/core__fact_events.sql
- models/core/core__fact_events.yml
- models/silver/silver___all_undecoded_instructions_data.sql
- models/silver/silver___inner_instructions.sql
- models/silver/silver___instructions.sql
- models/silver/silver___post_token_balances.sql
- models/silver/silver___pre_token_balances.sql
- models/silver/silver__events.sql
- models/silver/silver__events.yml
- models/silver/silver__transactions.sql
- models/silver/silver__votes.sql
- Per Dan's Request
- Added signers column w/ copied incremental logic at silver level. Testing a join at the core level as a view & table resulted in non-satisfactory query and FR performance.
> add signers column to events

- models/silver/silver__transactions.sql
- models/silver/silver__votes.sql
- temporarily reload larger range to mitigate partial loading
> temporarily reload larger range

- .github/workflows/dbt_test_hourly.yml
- tests/test_silver__transactions_partial_partitions.sql
- Add test to check bronze partitions are loaded properly into silver transactions and votes
> hourly test to check bronze partitions are loaded properly into silver

- .github/workflows/dbt_run_incremental.yml
- models/silver/nfts/silver__nft_mint_price_generic.sql
- Remove NFT models from 'exclude' list
- Change incremental logic back to standard
> Hotfix - revert NFT models incremental workflow

- .github/workflows/dbt_run_incremental.yml
- models/silver/nfts/silver__nft_sales_magic_eden_v2.sql
Revert back to standard incremental process following ad-hoc runs
> Hot fix/revert incremental ME v2

- .github/workflows/dbt_run_incremental.yml
Remove `initialization_pools_orca` from the exclusion for the incremental run
> remove init_pools_orca model from exclusion

- models/silver/silver__burn_actions.sql
- models/silver/silver__mint_actions.sql
Correct the key being searched for from 'multisigAuthority' to 'multisigMintAuthority'
> correct string to 'multisigMintAuthority'

- .github/workflows/dbt_run_incremental.yml
Add the initialization_pools_raydium to the incremental run by removing it from the `exclude` tag
> remove init_pools_raydium from exclusion

- models/streamline/streamline__all_unknown_block_txs_real_time.sql
temporarily disable the encoded tx check
> disable lookback on bronze data temp

- .github/workflows/dbt_run_streamline_get_blocks_real_time.yml
This is just to test the runner to see if it will schedule this job every 15mins
> temp workflow for testing use of new runner

- .github/workflows/dbt_run_incremental.yml
Remove nft_sales_amm_sell models from `exclude`
> enable nft_sales_amm_sell model

- models/core/core__fact_transactions.yml
Corrected the name for UNITS_LIMIT column in the yml file
> Fix UNITS_LIMIT col name

- macros/python/udfs.sql
- models/silver/silver__transactions.sql
- Reformat the UDF to include correct whitespaces
- Remove temporary null values now that the column is present
> Hot fix/reformat tx size python

- macros/run_sp_create_prod_clone.sql
Grant usage on solana_dev db to internal_dev role.
> grant internal_dev access to dev db

- models/silver/nfts/silver__nft_mint_price_generic.sql
Fixing instances where the minted NFT's minted were counted as payments
> exclude mint amounts from price

- models/silver/nfts/silver__nft_sales_hadeswap.sql
Include an extra on program ID, where the model was previously grabbing some unrelated events
> extra filter on program id

- macros/create_udfs.sql
- macros/streamline/snapshot_get_vote_accounts/run_sp_snapshot_get_vote_accounts.sql
- macros/streamline/snapshot_get_vote_accounts/sp_create_snapshot_get_vote_accounts.sql
- macros/streamline/snapshot_get_vote_accounts/udf_snapshot_get_vote_accounts.sql
- macros/streamline/sp_refresh_external_tables_full.sql
- models/bronze/bronze__vote_accounts.sql
- models/silver/validator/silver__snapshot_vote_accounts.sql
- models/silver/validator/silver__snapshot_vote_accounts.yml
- models/sources.yml
Bronze + silver tables for data from the getVoteAccounts rpc method.
> An 3028/vote account models

- macros/python/udfs.sql
initialize the match variable before the loop with a default value of None
> assign 'match' var in compute units udf

- models/bronze/bronze__stake_program_accounts.sql
- models/bronze/bronze__validators_app_api.sql
- models/silver/validator/silver__snapshot_stake_accounts.sql
- models/silver/validator/silver__snapshot_stake_accounts.yml
- models/silver/validator/silver__snapshot_validators_app_data.sql
- Create bronze + silver tables for stake program accounts
- adjustments to references for existing validator tables
> An 3127/stake program accounts

- .github/workflows/dbt_run_daily.yml
- dbt_project.yml
- macros/create_udfs.sql
- macros/streamline/snapshot_get_vote_program_accounts/run_sp_snapshot_get_vote_program_accounts.sql
- macros/streamline/snapshot_get_vote_program_accounts/sp_create_snapshot_get_vote_program_accounts.sql
- macros/streamline/snapshot_get_vote_program_accounts/udf_snapshot_get_vote_program_accounts.sql
- macros/streamline/sp_refresh_external_tables_full.sql
- models/bronze/bronze__vote_accounts.sql
- models/bronze/bronze__vote_accounts_extended_stats.sql
- models/silver/validator/silver__snapshot_validators_app_data.sql
- models/silver/validator/silver__snapshot_vote_accounts.sql
- models/silver/validator/silver__snapshot_vote_accounts.yml
- models/silver/validator/silver__snapshot_vote_accounts_extended_stats.sql
- models/silver/validator/silver__snapshot_vote_accounts_extended_stats.yml
- models/sources.yml
- add new vote accounts table + udf/sp's
- rename existing vote_accounts table to vote_accounts_extended_stats
- adjust naming accordingly
> An 3186/add vote program accounts table

- .github/workflows/dbt_run_weekly.yml
- macros/bronze_api/get_solscan_token_list.sql
- macros/bronze_api/get_token_metadata.sql
- models/silver/metadata/silver__solscan_tokens.sql
- models/sources.yml
- add solscan api to udfs
- run token update weekly for top 7500 tokens
> An 3272/solscan api key

- models/core/core__fact_swaps.sql
- models/core/core__fact_swaps.yml
- models/silver/swaps/silver__swaps.sql
- models/silver/swaps/silver__swaps.yml
- models/silver/swaps/silver__swaps_intermediate_generic.sql
- models/silver/swaps/silver__swaps_intermediate_generic.yml
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.yml
- models/silver/swaps/silver__swaps_intermediate_orca.sql
- models/silver/swaps/silver__swaps_intermediate_orca.yml
- models/silver/swaps/silver__swaps_intermediate_raydium.sql
- models/silver/swaps/silver__swaps_intermediate_raydium.yml
Extract indexes from the swap models to create a _log_id col.
> An 3339/index in swaps

- models/gold/core__dim_labels.yml
Add new 'bridge' label type to test
> add bridge type to check

- .github/workflows/dbt_run_daily.yml
- macros/bronze_api/get_block_production.sql
- models/silver/validator/silver__historical_block_production.sql
- models/silver/validator/silver__historical_block_production.yml
- models/silver/validator/silver__snapshot_block_production.sql
- models/silver/validator/silver__snapshot_block_production.yml
- models/sources.yml
- Create ingestion UDF for daily snapshot of block production data
-  table for historical block production data sent from Solana Foundation
> block_production model

- models/silver/nfts/silver__nft_sales_amm_sell.sql
Fix logic for AMM sales performed via Magic Eden
- separate sell and buy txs
> fix mev2 sell txs

- models/silver/liquidity_pool/silver__initialization_pools_raydium.sql
Update the instruction index for token accounts for newer raydium pool creation events
> fix account reference

- .github/workflows/dbt_run_daily.yml
- models/silver/validator/silver__historical_stake_account.sql
- models/silver/validator/silver__historical_validator_app_data.sql
- models/silver/validator/silver__historical_vote_account.sql
- models/sources.yml
- fix incorrect model name in github workflow
- update refs for historical validator models
> Hot fix/historic validator refs

- models/gold/core__fact_block_production.sql
- models/gold/core__fact_block_production.yml
- models/gold/core__fact_stake_accounts.sql
- models/gold/core__fact_stake_accounts.yml
- models/gold/core__fact_validators.sql
- models/gold/core__fact_validators.yml
- models/gold/core__fact_vote_accounts.sql
- models/gold/core__fact_vote_accounts.yml
- models/silver/validator/silver__historical_stake_account.sql
- models/silver/validator/silver__historical_validator_app_data.sql
- models/silver/validator/silver__historical_vote_account.sql
- models/silver/validator/silver__snapshot_block_production.sql
- models/silver/validator/silver__snapshot_stake_accounts.sql
- models/silver/validator/silver__snapshot_validators_app_data.sql
- models/silver/validator/silver__snapshot_vote_accounts.sql
- Create core tables from silver validator data
- adjust cols to array/object as needed
> An 3519/core validator tables

- .github/workflows/dbt_run_idls_history.yml
- .github/workflows/dbt_run_parser_program_historical.yml
- models/streamline/parser/streamline__all_undecoded_instructions_history.sql
- models/streamline/parser/streamline__idls_history.sql
1. update historical view to select events by program
2. create idls_history to track history of program events
3. create workflows
> An 3765/parser historical

- .github/workflows/dbt_run_parser_program_historical.yml
- offset job start time from real time parser
> offset times from realtime parser

- models/descriptions/burn_amount.md
- models/descriptions/signers.md
- models/descriptions/token_account.md
- models/gold/core/core__fact_burn_actions.sql
- models/gold/core/core__fact_burn_actions.yml
- models/gold/core/core__fact_mint_actions.sql
- models/gold/core/core__fact_mint_actions.yml
Create `fact_mint_actions` and `fact_burn_action` core tables
> An 3900/gold mint and burn actions

- .github/workflows/dbt_run_incremental.yml
- models/gold/nft/nft__fact_nft_sales.sql
- models/silver/accounts/silver__stake_account_ownership_events.sql
- models/silver/accounts/silver__token_account_owners.sql
- models/silver/accounts/silver__token_account_owners_intermediate.sql
- models/silver/accounts/silver__token_account_ownership_events.sql
- models/silver/nfts/silver___nft_distinct_mints.sql
- models/silver/nfts/silver__nft_bids_yawww.sql
- models/silver/nfts/silver__nft_sales_opensea.sql
- models/silver/nfts/silver__nft_sales_opensea_view.sql
- models/silver/nfts/silver__nft_sales_solport.sql
- models/silver/nfts/silver__nft_sales_yawww.sql
- models/silver/nfts/silver__nft_sales_yawww_view.sql
- models/silver/silver__signers_nfts_held.sql
- models/sources.yml
- set `enable = false` for models that were previously excluded in GH action workflow
- create views and sources for models used in gold views
> Sources and disable old models

- macros/bronze_api/get_solscan_token_list.sql
- models/silver/metadata/silver__solscan_tokens.yml
- decrease number of requests in single LQ call and use loop
- add recency test to silver table (weekly)
> An 3947/fix solscan token macro

- .github/workflows/dbt_run_idls_history.yml
- .github/workflows/dbt_run_parser_program_historical.yml
- Need to fix the paths in existing workflow jobs since I moved the files around
> fix path because model file was moved

- .github/workflows/dbt_run_helius_metadata.yml
> update helius job

- models/silver/nfts/silver__nft_mint_actions.sql
- models/silver/silver__mint_actions.sql
- models/silver/tokens/silver__token_mint_actions.sql
- Add incremental predicates for these 3 models because I noticed their `DELETE` statements were taking a long time
> add merge predicate to improve incremental run times

- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_historical.sql
- models/streamline/streamline__all_unknown_block_rewards_historical.sql
- modify backfill range
- add external table refresh on most recent batch in case there are issues with file registration by streamline
> An 4092/backfill block rewards

- .github/workflows/dbt_run_parser_program_historical.yml
- models/streamline/parser/history/streamline__all_undecoded_instructions_history.sql
> Tmp change history for jupv5 backfill

- models/silver/idls/silver__verified_user_idls.sql
- Check for error messages in individual decoder responses
- IDL is only valid if 75% of events are successfully decoded
> validate idls based on error rate

- models/silver/idls/silver__verified_idls.sql
- models/silver/idls/silver__verified_user_idls.sql
- Filter on `is_valid` for verified idls
> An 4190/fix idl verification

- models/gold/gov/gov__fact_rewards_rent.sql
- models/silver/rewards/silver__rewards_rent.sql
- models/silver/rewards/silver__rewards_rent_view.sql
- models/sources.yml
- disable silver.rewards_rent and add as source
- create view that selects from source
- update gold table to select from view
> disable rewards_rent

- models/gold/core/core__dim_labels.sql
- models/gold/core/core__dim_labels.yml
- models/gold/core/core__dim_tokens.sql
- models/gold/core/core__dim_tokens.yml
- models/gold/core/core__ez_events_decoded.sql
- models/gold/core/core__ez_events_decoded.yml
- models/gold/core/core__ez_signers.sql
- models/gold/core/core__ez_signers.yml
- models/gold/core/core__fact_blocks.sql
- models/gold/core/core__fact_blocks.yml
- models/gold/core/core__fact_decoded_instructions.sql
- models/gold/core/core__fact_decoded_instructions.yml
- models/gold/core/core__fact_events.sql
- models/gold/core/core__fact_events.yml
- models/gold/core/core__fact_transactions.sql
- models/gold/core/core__fact_transactions.yml
- models/gold/core/core__fact_transfers.sql
- models/gold/core/core__fact_transfers.yml
- models/silver/labels/silver__labels.sql
- models/silver/metadata/silver__token_metadata.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/silver/silver__blocks.sql
- models/silver/silver__events.sql
- models/silver/silver__signers.sql
- models/silver/silver__transactions.sql
- models/silver/silver__transfers.sql
- add export columns: <pk>, inserted_timestamp, and modified_timestamp to gold core
- adds _invocation_id to silver
> An 4116/new columns

- macros/create_sps.sql
- macros/sp_create_prod_clone.sql
- models/silver/accounts/silver__token_account_owners.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/silver/rewards/silver__rewards_fee.sql
- models/silver/rewards/silver__rewards_rent.sql
- models/silver/rewards/silver__rewards_staking.sql
- models/silver/rewards/silver__rewards_voting.sql
- models/silver/silver__events.sql
- models/silver/silver__transactions.sql
- models/silver/silver__transfers.sql
- models/silver/silver__votes.sql
- models/silver/swaps/silver__swaps_intermediate_generic.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.sql
- models/silver/swaps/silver__swaps_intermediate_orca.sql
- models/streamline/parser/streamline__complete_decoded_instructions.sql
- Drop search optimization on large tables after dev is refreshed
- Prevent search optimization from being added in non-prod databases
> prevent search optimization on dev tables

- .github/workflows/dbt_run_deploy_udfs_and_sps.yml
- New workflow to deploy changes on UDFs and SPs whenever the macro folder changes
> An 4332/auto deploy udf changes

- models/silver/rewards/silver__rewards_fee.sql
- Fix issue with `reward_fees` logic that is creating duplicate unique key entries
> do qualify after union

- models/silver/rewards/silver__rewards_rent.sql
- models/silver/rewards/silver__rewards_staking.sql
- models/silver/rewards/silver__rewards_voting.sql
- Apply [hotfix](https://github.com/FlipsideCrypto/solana-models/pull/434) for remaining reward models
> add qualify after union

- models/silver/parser/silver__decoded_instructions.sql
> try to limit partition scans

- models/bronze/streamline/bronze__streamline_FR_decoded_instructions_2.sql
- models/bronze/streamline/bronze__streamline_decoded_instructions_2.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_2.sql
- Change partition grain to hourly 
- Use new hourly partition column to better prune external table lookups
> use hourly grain to better prune data

- models/silver/idls/silver__verified_user_idls.sql
- Fix issue where IDLs that have been resubmitted were not resent through the idl verification process
> fix updated idls for previously invalid not being retried

- models/gold/defi/defi__fact_token_burn_actions.sql
- models/gold/defi/defi__fact_token_burn_actions.yml
- models/gold/defi/defi__fact_token_mint_actions.sql
- models/gold/defi/defi__fact_token_mint_actions.yml
- models/silver/silver__burn_actions.sql
- models/silver/silver__burn_actions.yml
- models/silver/tokens/silver__token_burn_actions.sql
- models/silver/tokens/silver__token_burn_actions.yml
- models/silver/tokens/silver__token_mint_actions.sql
- models/silver/tokens/silver__token_mint_actions.yml
Add token_account column to token_mint_actions + token_burn_actions
> add token_account

- .github/workflows/dbt_run_deploy_seeds.yml
- .github/workflows/dbt_run_deploy_udfs_and_sps.yml
- Full refresh seed files on any change in `data` folder
> auto re-deploy seed files on change

- .github/workflows/dbt_run_incremental_non_core.yml
- macros/helpers/decoded_instructions_backfill_helpers.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_2.sql
- Patch fix for files not being auto registered via snowpipe in times of high load 
- Manually force file registration with 1 hour lookback
- Performed as pre-hook where the bronze decoded instructions table is referenced
> An 4419/force file registration

- macros/helpers/decoded_instructions_backfill_helpers.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_2.sql
- revert changes made here [https://github.com/FlipsideCrypto/solana-models/pull/448](https://github.com/FlipsideCrypto/solana-models/pull/448)
> remove macro and pre-hooks

- models/silver/idls/silver__verified_idls.sql
- models/silver/idls/silver__verified_user_idls.sql
- Always re-verify and accept updates to existing program idls
> An 4427/reverify all newly submitted idls

- models/silver/parser/silver__decoded_instructions.sql
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_2.sql
- Change lookback logic to use `_inserted_timestamp` instead of current
- Run as a inline pre-hook so we dont have to run additional subqueries
- Adjust lookback period
> use _inserted_timestamps as lookback basis not current timestamp

- .github/workflows/dbt_run_decode_instructions_orchestrator.yml
- .github/workflows/dbt_run_decode_instructions_pyth.yml
- models/streamline/decode_instructions/streamline__decode_instructions_2_pyth_realtime.sql
- Add view for real time pyth decoding
- temporarily pointed at backfill queue (has more processing power). Will monitor and switch when caught up
- Add workflow job for real time pyth decoding
- Remove placeholder workflow
> add workflow for pyth realtime

- .github/workflows/dbt_run_incremental_decoded_instructions_temporary.yml
- models/silver/parser/silver__decoded_instructions_2.sql
Will run a clone to get the full table copied to test performance 1-1:
create Transient table solana_dev.silver.decoded_instructions_2  clone solana_dev.silver.decoded_instructions
> decoded_instructions_temp

- .github/workflows/dbt_run_nft_compressed_mints_backfill.yml
- .github/workflows/dbt_run_nft_compressed_mints_realtime.yml
- data/github_actions__workflows.csv
- macros/helpers/nft_compressed_mints_backfill_helpers.sql
- Backfill macros to do bronze_api nft compressed mints parsing backfill
- Add/Change workflow jobs
- Current real time job is poorly named
- Add new job to do the backfill
> An 4435/compressed mints backfill helpers

- macros/helpers/nft_compressed_mints_backfill_helpers.sql
- Adjust size to match fixes in realtime job
> match batch size of realtime job

- .github/workflows/dbt_test_hourly.yml
- tests/test_streamline__complete_decoded_instructions_2__missing.sql
- Check for missing completed data within a 1 hour window from 3 hours ago
- Example:  if current time is `10:00:00` the test would be for data loaded into bronze `>= 07:00:00 and  <= 07:59:59`
- Schedule the test to run hourly
> add hourly test to check missing completed

- models/streamline/decode_instructions/streamline__decode_instructions_2_pyth_realtime.sql
- Logic used by backfill process seems to perform much better (ie. `select 1 from <view> limit 1` is much faster on backfills than for realtime)
- Backfill select finishes in seconds vs. realtime select currently takes multiple minutes
- Update realtime logic to match backfill
- 150k block lookback
- remove the join since we are always selecting the pyth contract
> optimize pyth realtime select performance

- models/streamline/decode_instructions/streamline__complete_decoded_instructions_2.sql
- Need 5min lookback to make sure we don't miss any late arriving files
> same race condition as silver table, add 5min lookback

- models/silver/silver__votes_agg_block.sql
- Fix bad join causing certain blocks to not be included in the output
> remove inner join, can get timestamp in one query

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
- Same idea as (https://github.com/FlipsideCrypto/solana-models/pull/508)
- This wont have as big of a performance boost because most of the execution time is due to having to scan events
> add min block as static value to ensure partition pruning

- .github/workflows/dbt_test.yml
- .github/workflows/dbt_test_weekly.yml
- tests/test_silver__decoded_instructions_combined_error_threshold_7_days.sql
- tests/test_silver__decoded_instructions_combined_static_error_threshold_7_days.sql
- Add tags to weekly tests
- Run using tags
- Exclude from daily test runs using tags
> add tests to tags and include/exclude using tag

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
- Add jupiter governance program to exclude list for inner instructions with only 1 account
> add jup gov program to list

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
> Add inner instruction decode ignore list

- macros/helpers/decoded_instructions_backfill_helpers.sql
- Add zpad to view block names so that they are always in descending order
- Allow setting custom priority value as part of view name
> add lpad zeros to view name, fix set formatting

- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- Increase # of items per request
- This will fix issue with current process where the number of cnft mints for a given `_inserted_timestamp` is `>=` the # of requests causing the process to request the same items again on the next iteration
- Fix formatting of set query for better readability
```
14:26:24  1 of 1 OK created sql incremental model bronze_api.parse_compressed_nft_mints .. [SUCCESS 114 in 109.74s]
14:26:24  Finished running 1 incremental model, 11 hooks in 0 hours 2 minutes and 4.08 seconds (124.08s).
14:26:24  
14:26:24  Completed successfully
14:26:24  
14:26:24  Done. PASS=1 WARN=0 ERROR=0 SKIP=0 TOTAL=1
```
> increase throughput and fix formatting for set query

- models/descriptions/backfill_status.md
- models/descriptions/date_submitted.md
- models/descriptions/earliest_decoded_block.md
- models/descriptions/first_block_id.md
- models/descriptions/is_valid.md
- models/descriptions/submitted_by.md
- models/gold/core/core__dim_idl.sql
- models/gold/core/core__dim_idl.yml
- models/gold/core/core__dim_idls.sql
- models/gold/core/core__dim_idls.yml
- models/silver/idls/silver__idl.sql
- models/silver/idls/silver__idl.yml
- models/silver/idls/silver__idls.sql
- models/silver/idls/silver__idls.yml
- Include additional information in the gold IDL table. Based on user requests for more visibility on decoding process
> update idl table

- models/silver/parser/silver__decoded_instructions_combined.sql
- models/silver/silver__events.sql
- models/silver/silver__transactions.sql
- models/silver/silver__transfers.sql
- models/silver/silver__votes.sql
- models/silver/swaps/silver__swaps_intermediate_generic.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv6.sql
- models/silver/swaps/silver__swaps_intermediate_orca.sql
- Define search optimization for tables at column level
> update SO configurations

- .github/workflows/dbt_run_nft_compressed_mints_sales_realtime.yml
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_sales_magic_eden.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_sales_solsniper.sql
Subset of https://github.com/FlipsideCrypto/solana-models/pull/543/files
> workflow changes

- models/silver/nfts/silver__nft_sales_magic_eden_cnft.sql
- models/silver/nfts/silver__nft_sales_magic_eden_cnft.yml
- models/silver/nfts/silver__nft_sales_solsniper_cnft.sql
- models/silver/nfts/silver__nft_sales_solsniper_cnft.yml
subset of https://github.com/FlipsideCrypto/solana-models/pull/543
> final silver cnft sales model

- models/silver/program_logs/silver__transaction_logs_program_data.sql
- Add `silver__transaction_logs_program_data` to core schedule
Sample [incremental](https://github.com/FlipsideCrypto/solana-models/actions/runs/9466836189/job/26079432590) on M warehouse
```
13:51:05  1 of 1 OK created sql incremental model silver.transaction_logs_program_data ... [SUCCESS 151053 in 24.39s]
```
> add to core schedule

- models/gold/defi/defi__ez_dex_swaps.sql
- models/gold/defi/defi__ez_dex_swaps.yml
Create defi.ez_dex_swaps view
- following naming conventions present in fact_swaps
- no raw amounts as those are not tracked in Solana tables
> ez_dex_swaps

- models/descriptions/balances/balances.md
- models/gold/core/core__fact_sol_balances.sql
- models/gold/core/core__fact_sol_balances.yml
- models/gold/core/core__fact_token_balances.sql
- models/gold/core/core__fact_token_balances.yml
- models/silver/balances/silver__sol_balances.sql
- models/silver/balances/silver__sol_balances.yml
- models/silver/balances/silver__token_balances.sql
- models/silver/balances/silver__token_balances.yml
- models/silver/idls/silver__verified_user_idls.sql
create silver and core models for `sol_balances` and `token_balances`
- join `fact_token_balances` to `token_account_owners` to get true `owner`
-- incrementals on medium (for tables)
`1 of 2 OK created sql incremental model silver.sol_balances .................... [SUCCESS 1731399 in 17.62s]`
`2 of 2 OK created sql incremental model core.fact_sol_balances ................. [SUCCESS 1731399 in 25.73s]`
`1 of 2 OK created sql incremental model silver.token_balances .................. [SUCCESS 904200 in 19.12s]`
`2 of 2 OK created sql incremental model core.fact_token_balances ............... [SUCCESS 904200 in 171.65s]`
-- tests on m
```
00:48:58  Finished running 51 tests, 11 hooks in 0 hours 15 minutes and 30.00 seconds (930.00s).
00:48:58  
00:48:58  Completed successfully
```
> balance models

- models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql
- Fix issue with incremental will modify old records incorrectly due to the fact that the model uses a window function to create column values
- Any inner swap in an incremental subset will now re-ingest the entire transaction through the model logic so that the window function logic will work properly
> Fix inner swaps incremental issue

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
- Remove Phoenix logs from being sent as requests to instructions decoder
- Add Phoenix logs to requests for logs decoder
> Decode phoenix logs

- .github/workflows/dbt_docs_update.yml
Prevent `dbt_docs_update` job from running queries under `{% if execute %}`
> --no-compile flag and add dbt ls

- models/silver/parser/silver__decoded_instructions_combined.yml
`4 of 25 PASS dbt_utils_relationships_where_silver__decoded_instructions_combined_meteora_liquidity_pool_actions_tx_id  [PASS in 6.51s]`
> update meteora test

- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
- Add jup DCA program to log decoding realtime
> add dca program

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.yml
- tests/test_silver__decoded_logs_jupiter_dca_signers.sql
```
15:57:31  1 of 2 OK created sql incremental model silver.swaps_intermediate_jupiterv6_2 .. [SUCCESS 77138 in 114.23s]
```
```
16:02:08  36 of 39 PASS test_silver__decoded_logs_jupiter_dca_signers .................... [PASS in 5.59s]
```
> add to dca keeper whitelist

- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
- Whitelist layerzero program `7a4WjyR8VZ7yZz5XJAKm39BUGn5iT9CKcv2pmG9tdXVH` for realtime logs decoding
> add layerzero to realtime log decoding:

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.yml
- Update test predicate for DCA related columns
> update tests now that data is backfilled

- macros/python/udfs.sql
- Modify `udf_get_logs_program_data` to also output records if program logs are base64 encoded. This is backwards compatible.
Loaded `2023-01-01` in dev
```
-- Everything in prod should be output by the new version
select transaction_logs_program_data_id
from solana.silver.transaction_logs_program_data
where block_timestamp::date = '2023-01-01'
except 
select transaction_logs_program_data_id
from solana_dev.silver.transaction_logs_program_data
where block_timestamp::date = '2023-01-01';
```
```
-- We should have new output in dev
select transaction_logs_program_data_id
from solana_dev.silver.transaction_logs_program_data
where block_timestamp::date = '2023-01-01'
except 
select transaction_logs_program_data_id
from solana.silver.transaction_logs_program_data
where block_timestamp::date = …
```
> include program logs that are base64 strings

- models/gold/gov/gov__fact_validators.yml
- models/silver/silver__transactions.sql
Remove `not null` tests for columns where the API returns nulls
> Hot fix/gold validator tests

- models/silver/backfill/silver__backfill_transactions_units_consumed.sql
- add qualify to address duplicate row error   `100090 (42P18): Duplicate row detected during DML action`
> add qualify

- models/silver/swaps/meteora/silver__swaps_intermediate_meteora.sql
- Default these edge cases where there is no to mint / amount transferred back to the swapper even though it is a meteora swap event. This removes the logic aimed to fix this in this previous [PR](https://github.com/FlipsideCrypto/solana-models/pull/667). The assumption made there was this only happens in jupiter related meteora swaps but that has not held true
- Default the to amount/mint to `0/WSOL` when it meets criteria for these edge cases. These values were chosen based on what the Jupiter swap events show when these edge cases appear as part of a Jupiter swap
- `~88` transactions are affected
```
with prod_issues as (
select *
from solana.silver.swaps_intermediate_meteora
where to_amt is null or to_mint is null
)
select 
s.to_amt, s.to_mint, t.*
from prod_issues AS t
left join …
```
> Fix null to amount/mint for meteora edge cases

- models/gold/defi/defi__ez_dex_swaps.yml
- models/gold/defi/defi__fact_swaps.yml
- fix description for `program_id`
> fix program_id desc

- .github/workflows/dbt_run_daily.yml
- remove file path for `silver__daily_signers` which has been moved to `silver/non_core` folder
> remove file path

- models/silver/swaps/raydium/silver__swaps_intermediate_raydium_v4_amm.sql
Logic added to base query (similar to meteora and other swap tables) to get distinct tx_id's because the incremental interval on `_inserted_timestamp` occasionally only grabs one part of the swap.
ie tx `42a7GeWqCVi8p3e5EGqKh6pcYnuqK4c6Kjg9ZmiN7SKe1aFhtvUDQJrPiMinTwvKPeAcTVVYjXE4TH33mMH52yD5`
> get distinct txs

- models/silver/core/silver__transfers.sql
Starting some time after `2024-07-01` there has been a significant change (or at least usage of the change) of how some `WSOL` transfers are shown in the underlying data. The key difference for these transfers is that they are not in post/pre token balances tables AND the transfers is not listed as having transferred any `lamports`. 
To identify these as `WSOL` transfers, we have to look at the transaction account keys and see if the account is listed there. If it is listed there is must be a `SOL` or `WSOL` transfer and since these are called from the `spl-transfer` program, it must be `WSOL`. 
This PR is aimed to fix the data moving forward. Due to the size of this table, backfilling will require an alternative to just re-running the data.
Tested new logic in DEV for transfers `>= …
> match to account keys to check that it is wsol mint transfer

- models/gold/gov/gov__fact_rewards_fee.sql
- models/gold/gov/gov__fact_rewards_fee.yml
Remove `vote_pubkey` column from `fact_rewards_fee`
> remove vote_pubkey

- models/streamline/core/realtime/streamline__block_txs_2.sql
Update the streamline 2.0 block txs minimum starting partition
> update partition start min

- models/streamline/core/realtime/streamline__block_txs_2.sql
Add retry logic for when third party source has different tx count than what we have in silver
> add third party discrepancy retries

- models/gold/marinade/marinade__ez_native_staking_actions.sql
> add meta tags

- .github/workflows/dbt_run_stage_block_txs.yml
Fix the name in the dbt command
> hotfix stage bronze block txs workflow command

- tests/test_silver__transactions_and_votes_missing_7_days.sql
- Refactor `test_silver__transactions_and_votes_missing_7_days` by changing the `UNION` to `UNION ALL` and instead using `QUALIFY row_number()` to deduplicate which should be faster for large datasets
- I tried other methods, like `FULL OUTER JOIN` or `count(DISTINCT)` but `row_number()` performed best for exact count matching
`dbt test -s test_silver__transactions_and_votes_missing_7_days -t prod`
```
17:07:22  1 of 1 PASS test_silver__transactions_and_votes_missing_7_days ................. [PASS in 776.16s]
```
Existing run times sample
> Refactor hourly tx count test

- models/streamline/decode_logs/streamline__decode_logs_2_realtime.sql
- Refactor `decode_logs_2_realtime`
- Use `silver.events_inner`
- Reference programs to decode as a static list
Existing
New (executed using prod upstreams)
Data in DEV
```
select count(*) from solana_dev.streamline.decode_logs_2_realtime_test;
```
> refactor decoded logs realtime to improve run time

- models/gold/core/core__fact_events_inner.sql
- models/silver/core/silver__events_inner.sql
add `program_id` and `instruction_program_id` to `events_inner` clustering
> add program to cluster

- models/silver/nfts/silver__nft_mints.sql
- models/silver/nfts/silver__nft_mints.yml
Fixing NFT Mints duplicate unique ID error. caught from daily test.
> AN-5834 NFT Mints Error Fix

- models/gold/defi/defi__fact_bridge_activity.sql
- models/gold/defi/defi__fact_bridge_activity.yml
- models/gold/gov/gov__fact_gauges_votes.sql
- models/gold/gov/gov__fact_gauges_votes.yml
- models/gold/gov/gov__fact_gov_actions.sql
- models/gold/gov/gov__fact_gov_actions.yml
- models/gold/gov/gov__fact_proposal_creation.sql
- models/gold/gov/gov__fact_proposal_creation.yml
- models/gold/nft/nft__fact_nft_mints.sql
- models/gold/nft/nft__fact_nft_mints.yml
- models/gold/price/price__ez_asset_metadata.sql
- models/gold/price/price__ez_asset_metadata.yml
- models/gold/price/price__ez_prices_hourly.sql
- models/gold/price/price__ez_prices_hourly.yml
Convert gold views with UNIONS into tables
- update tests
FR on 2xl:
```
17:03:01  2 of 7 OK created sql incremental model gov.fact_gauges_votes .................. [SUCCESS 1 in 7.43s]
17:03:01  3 of 7 OK created sql incremental model gov.fact_gov_actions ................... [SUCCESS 1 in 7.55s]
17:03:14  6 of 7 OK created sql incremental model price.ez_asset_metadata ................ [SUCCESS 1 in 13.22s]
17:18:42  2 of 4 OK created sql incremental model gov.fact_proposal_creation ............. [SUCCESS 1 in 6.61s]
17:18:45  4 of 4 OK created sql incremental model price.ez_prices_hourly ................. [SUCCESS 1 in 9.63s]
17:18:47  1 of 4 OK created sql incremental model defi.fact_bridge_activity .............. [SUCCESS 1 in 11.83s]
17:20:00  3 of 4 OK created sql incremental model …
```
> convert views to tables

- models/silver/bridges/silver__bridge_wormhole_transfers.sql
- models/silver/bridges/silver__bridge_wormhole_transfers.yml
Fixing dupes on Wormhole transfers. Issue caused by outbound cte not having enough filters that it includes burns on Meteora too. Caught from daily test.
> AN-5835-Wormhole-Fix

- models/gold/defi/defi__ez_dex_swaps.yml
- models/gold/defi/defi__fact_swaps.sql
- models/gold/defi/defi__fact_swaps.yml
- models/silver/swaps/pumpfun/silver__swaps_pumpswap.sql
- models/silver/swaps/pumpfun/silver__swaps_pumpswap.yml
Add new Pumpswap dex to `fact_swaps`
- fr on 2xl:
`20:20:07  1 of 1 OK created sql incremental model silver.swaps_pumpswap .................. [SUCCESS 1 in 118.74s]
`
- inc run for gold:
`20:32:47  1 of 1 OK created sql incremental model defi.fact_swaps ........................ [SUCCESS 45481022 in 203.05s]
`
- tests passed on silver:
```
20:28:45  Finished running 17 data tests, 6 project hooks in 0 hours 0 minutes and 45.53 seconds (45.53s).
20:28:46  Completed successfully
20:28:46  Done. PASS=17 WARN=0 ERROR=0 SKIP=0 TOTAL=17
```
> add pumpswap

- package-lock.yml
- packages.yml
Update various package dependencies to their latest versions to ensure compatibility and access to new features.
> Update package dependencies in package-lock.yml and packages.yml

- models/gold/defi/defi__ez_dex_swaps.sql
- models/gold/defi/defi__fact_token_burn_actions.sql
- models/gold/defi/defi__fact_token_mint_actions.sql
- models/gold/nft/nft__dim_nft_metadata.sql
- models/gold/nft/nft__fact_nft_burn_actions.sql
- models/gold/nft/nft__fact_nft_mint_actions.sql
- models/silver/metadata/helius/silver__helius_cnft_metadata.sql
- models/silver/metadata/helius/silver__helius_nft_metadata.sql
- models/silver/nfts/silver__nft_burn_actions.sql
- models/silver/nfts/silver__nft_mint_actions.sql
- models/silver/tokens/silver__token_burn_actions.sql
- models/silver/tokens/silver__token_mint_actions.sql
Convert views in NFT and DEFI schema to tables
To update without downtime to users:
1. Add `_2` to models and run locally in prod
2. drop views and rename `_2` tables ie `ALTER TABLE solana.defi.fact_token_burn_actions_2 RENAME TO solana.defi.fact_token_burn_actions;`
3. Double-check grants
> convert nft and defi gold views

- models/descriptions/__overview__.md
- models/gold/defi/defi__ez_dex_swaps.yml
- models/gold/defi/defi__fact_swaps.yml
- models/gold/defi/defi__fact_swaps_jupiter_inner.yml
- models/gold/defi/defi__fact_swaps_jupiter_summary.yml
Add link for doc + video to overview and swaps tables.
> add swaps faq links

- macros/tests/reference_tx_count_comparison.sql
- models/gold/defi/defi__ez_dex_swaps.yml
Test to compare counts of gold table with its reference to ensure all records exist
- successful test run:
```
20:52:27  1 of 1 START test reference_tx_count_comparison_defi__ez_dex_swaps_tx_id__defi__fact_swaps  [RUN]
20:52:36  1 of 1 PASS reference_tx_count_comparison_defi__ez_dex_swaps_tx_id__defi__fact_swaps  [PASS in 9.36s]
```
> add ref count test

- .github/workflows/dbt_run_daily.yml
set new env var `WAREHOUSE_LARGE` = `DBT_CLOUD_LARGE`
> use large warehouse

- models/bronze/prices/bronze__complete_token_prices.sql
- models/descriptions/bridge/bridge_activity.md
- models/descriptions/prices/prices.md
- models/gold/defi/defi__ez_bridge_activity.sql
- models/gold/defi/defi__ez_bridge_activity.yml
- models/gold/defi/defi__ez_dex_swaps.sql
- models/gold/defi/defi__ez_dex_swaps.yml
- models/gold/defi/defi__ez_liquidity_pool_actions.sql
- models/gold/defi/defi__ez_liquidity_pool_actions.yml
- models/gold/price/price__ez_prices_hourly.sql
- models/gold/price/price__ez_prices_hourly.yml
- models/silver/prices/silver__complete_token_prices.sql
add `is_verified` columns to tables using prices
> verified pricing

- models/silver/validator/silver__snapshot_vote_accounts.sql
Handle records that contain nanosec timestamps and convert properly
> handle nanosecond timestamps

- models/silver/lending/kamino/silver__lending_kamino_withdraws.sql
Use `transfers` table to correctly get the `amount`
> fix amount logic

- models/descriptions/columns/active_stake_validator.md
Be more explicit in the amount being in Lamports and how to convert to SOL
> update desc for validator amount
