- macros/task_run_sp_create_prod_clone.sql
- tasks are suspended by default on creation.  Add statement to start it after create.
> set task to resumed state after create

- models/silver/silver__events.sql
- models/silver/silver__staking_lp_actions.sql
- Add table for `staking` actions
- Change cluster keys for `events`.  Using `ingested_at` for cluster key to stay consistent with our other silver tables that are used to build downstream.  Also adding `program_id` since we will likely be getting events belonging to specific programs.
> An 837/create lp actions

- models/silver/silver__gauges_votes_saber.yml
- models/silver/silver__gov_actions_saber.yml
- After investigating saber gov actions model recency test failure, it has been determined that this was due to true inactivity.  Tests txs were made on 5/16 to confirm current logic still works for locks/unlocks and they showed up properly in our model.  As a result, we are increasing the recency window to 7 days instead of 2 days.
> update to check 7 day window instead of 2

- tests/silver__transactions__block_id-assert-no-gaps.sql
- Gaps tests are failing for current date when the test is run due to how data comes in where it is not guaranteed to come in by contiguous blocks. I have verified over the last few days that the "gaps" resolve themselves on the next incremental as the data is actually there in the chainwalkers database.
> exclude current date from gap test

- models/silver/silver__nft_sales_smb.yml
- models/silver/silver__nft_sales_solport.yml
Per our resident solana expert @mdill89 we can turn the recency tests off for these models
`Solana monkey business one they told people to start using magic eden because there was a potential bug in their marketplace`
`Solport i think just has very low volume to almost no volume outside their launchpad`
> turn off recency test

- models/descriptions/gov_action_escrow_account.md
- models/silver/silver__gauges_votes_saber.sql
- models/silver/silver__gov_actions_saber.sql
- models/silver/silver__gov_actions_saber.yml
- Fix gov actions table for Saber.  This was missing transactions from 3rd party apps that were approved to lock tokens staked on their app and vote on behalf of other users.  These apps do not interact with the tribeca program directly but as an inner_instruction instead
- Fix gauge votes table for Saber. This was including non-saber gauge voting.  Old assumption was the program_id was sufficient to filter out these but it is not.  Changed to filter on the Saber gaugemeister as well which is included as the 1st account in a voting instruction.
- Added escrow_account to gov_actions table, this is not used in the fix, but could be useful down the line so i decided to add it just at the silver layer.
> An 1369/fix saber gov tables

- tests/silver__inner_instructions__program_id-assert-not-null.sql
Inner instructions test for Solana. We can have a small amount of bad inner instructions at any time, but should be caught by a test on the platform side and fixed by the next incremental run. So therefore there is a tolerance for bad instructions.
> An 1030 inner instructions test

- macros/create_udfs.sql
- macros/python/udfs.sql
- models/silver/silver__transactions.sql
- Using python UDF to get signers from the accounts array insteads of using CTEs.  There was an issue w/ the old data where the signers array was created out of order...however I could not recreate the issue as reloading the table generated the correct ordering.  Changing to python will guarantee the ordering based on code we write so will no longer be a black box.  Side benefit, using UDF seems to load 2x faster on incremental.
> use python to get signers from accts

- models/silver/silver__proposal_votes_realms.sql
- models/silver/silver__proposal_votes_realms.yml
Vote options are found in the transaction log. Yes and no votes have two separate log structures. 
There is a default program ID for realms that starts with GovER... However, if you write your own gov contract your space will have a unique program ID. There are multiple important spaces, such as Mango Markets, Serum, and Orca that utilize their own program ID. Labels for all the governance spaces' program IDs were uploaded from the Solana labs github to the labels table and pulled in via a CTE to this model to ID votes that occur on Realms. 
The final "WHERE" clause is necessary to correctly represent three transactions in which two vote accounts were created and two votes occurred within the same transaction. These "double" votes were done by the same voter on the same transaction. The …
> An 1719 realms

- models/core/core__ez_staking_lp_actions.sql
- Current model is referencing wrong column, all the validator names are "solana validator" instead of the "address name" which is the name of that specific validator.
> validator name referencing wrong labels column

- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_historical.sql
- models/streamline/streamline__all_unknown_block_rewards_historical.sql
- models/streamline/streamline__all_unknown_block_txs_historical.sql
- models/streamline/streamline__all_unknown_blocks_historical.sql
- models/streamline/streamline__complete_block_rewards.sql
- models/streamline/streamline__complete_block_txs.sql
- Update streamline models to backfill new set of blokcs
- Update block txs schedule to twice an hour because lambda is now configured to run for full 15mins + the amount of data loaded takes >10mins to refresh the tables before a new set of blocks can be retrieved for processing
> An 1971/update streamline backfill models

- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_historical.sql
- macros/streamline/bulk_get_block_rewards/task_bulk_get_block_rewards_real_time.sql
- macros/streamline/bulk_get_block_rewards/udf_bulk_get_block_rewards.sql
- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_historical.sql
- macros/streamline/bulk_get_block_txs/task_bulk_get_block_txs_real_time.sql
- macros/streamline/bulk_get_block_txs/udf_bulk_get_block_txs.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_historical.sql
- macros/streamline/bulk_get_blocks/task_bulk_get_blocks_real_time.sql
- macros/streamline/bulk_get_blocks/udf_bulk_get_blocks.sql
- models/streamline/streamline__all_unknown_block_rewards_real_time.sql
- models/streamline/streamline__all_unknown_block_txs_real_time.sql
- models/streamline/streamline__all_unknown_blocks_real_time.sql
- Add streamline resources to support getting chain head data
- Remove table refresh steps from streamline tasks, this is now done in streamline itself
> An 1981/update streamline for chainhead

- models/silver/silver__transactions2.sql
- reducing batch size because we are now getting into more recent backfills which were changed to ~200k blocks per batch vs. 45k blocks + these blocks hold more data
> reduce batch load size

- models/silver/silver__transactions2.sql
- models/silver/silver__votes2.sql
- don't try to get block_timestamps for blocks before `39824213`, pretty much they all have null timestamps from the node.
> pretty much all blocks before this have null timestamps

- models/silver/nfts/silver__nft_mint_price_generic2.yml
- models/silver/nfts/silver__nft_sales_magic_eden_v1_2.sql
- models/silver/nfts/silver__nft_sales_magic_eden_v1_2.yml
- models/silver/nfts/silver__nft_sales_magic_eden_v2_2.yml
- models/silver/silver___inner_instructions2.yml
- models/silver/silver___instructions2.yml
- models/silver/silver___post_token_balances2.yml
- models/silver/silver___pre_token_balances2.yml
- models/silver/silver__mint_actions2.yml
- Create .yml files for new models based on streamline data sources
- Update block_id filter range in `nft_sales_magic_eden_v1_2` to be consistent
> An 2258/tests for streamline based models

- tests/test_silver__blocks_gaps.sql
- Modify the block gaps test to output the full possible gap range.  Previous edition was flawed because it gave only 1 block id per gap...meaning if there was a gap of 100 blocks missing, we would need to run this 100 times for it to show.
> output gap range instead of single block id

- models/silver/silver__transactions.sql
- models/silver/silver__transactions.yml
- expose new `address_table_lookups` col that is relevant for `version 0` transactions
> expose address table lookups col

- models/silver/nfts/silver__nft_bids_yawww.yml
- Making the interval larger on the recency test for yawww bids.  I created a bid myself today and it is reflected in the model so I don't think there is an issue here with the code / nothing has changed programmatically on yawww's end
`select block_timestamp::date, count(*)
from solana.silver.nft_bids_yawww
group by 1
order by 1 desc;`
> make recency test larger interval

- models/silver/gauges/silver__gauges_votes_marinade.yml
There can be multiple days where no gauge votes occur, so the test for recency was increased to 14 days.
> increase date interval for recency test

- .github/workflows/dbt_run_incremental.yml
- packages.yml
- hotfix to allow solana to run on dbt 1.2.0
> allow solana to run on dbt 1.2

- models/silver/swaps/silver__swaps_intermediate_generic.sql
- models/silver/swaps/silver__swaps_intermediate_jupiterv4.sql
- models/silver/swaps/silver__swaps_intermediate_orca.sql
- models/silver/swaps/silver__swaps_intermediate_raydium.sql
Remove joins with the `transaction` table, because the `events` table now contains the `signers` column. This fixes the 'ambiguous column' error that occurred.
> remove join with transactions table

- models/streamline/streamline__all_unknown_block_txs_real_time.sql
Add logic to find transactions that are still encoded, to identify the blocks that need to be ingested with decoded data.
> Hot fix/identify encoded transactions

- models/silver/nfts/silver__nft_mints.yml
- Only test data from previous day, this is getting full refreshed daily, current date data may have some missing mints because data points may come in out of sync and this model requires all the data points to be there for it to give correct data for a row
> this model gets full refreshed daily, should test items <= prev day

- models/silver/silver__daily_signers.sql
- Our underlying tables have grown to a size where snowflake is no longer respecting the dynamic query pruning and requires a literal or static value.  See one reason https://community.snowflake.com/s/article/Pruning-is-not-happening-subquery.
- This is a temporary fix to limit the scan to last 7 days worth of data.  Any backfills required beyond this point will need a manual adjustment until a longer term fix is in place.
> temporary fix to avoid full table scan on underlying

- models/silver/nfts/silver__nft_bids_yawww.yml
- models/silver/nfts/silver__nft_sales_yawww.yml
The Yawww platform does not have much volume, so recency tests were adjusted:
- For NFT sales, increase the recency time interval to 14 days
- For NFT bids, remove the recency test as it was discussed that removing this completely would be appropriate.
> An 2678/yawww recency

- .github/workflows/dbt_run_adhoc.yml
- .github/workflows/dbt_run_dev_refresh.yml
- .github/workflows/dbt_run_incremental.yml
- models/silver/nfts/silver__nft_mint_price_generic.sql
- remove concurrency tag from adhoc job to allow multiple simultaneous runs
- revert the nft_mint_generic_price models to normal incremental, and remove it from the excluded models
- pause dev refresh
> Hot fix/revert gen nft model

- models/silver/silver__burn_actions.sql
There is a large gap in the early block_ids around 3400000 where there is not a burn_action present in the next 4 million blocks, so the batch_load never loads past that. The batch_load interval is updated to address that.
> adjust batch_load interval

- models/silver/accounts/silver__token_account_ownership_events.sql
- Put the parsed mint path into the correct select statement.  Was meant for the `initializeAccount...` select but was put into the `assign...` on accident
> put the path to mint in the wrong select

- models/silver/liquidity_pool/silver__initialization_pools_raydium.yml
Increasing range for recency test since new Raydium pools are not being created every other day.
> increase recency test interval for Raydium pool creation

- .github/workflows/dbt_run_incremental.yml
Turn on incremental for `liquidity_pool` models which is the cause of the recency failures for the `initialization_pool` tables
> enable liquidity_pool models

- models/silver/liquidity_pool/silver__initialization_pools_orca.yml
- models/silver/liquidity_pool/silver__initialization_pools_raydium.yml
Increase the recency test interval to 14 days for the creation of new pools in Orca + Raydium.
> Increase recency test interval

- models/descriptions/__overview__.md
Create overview page for Solana documentation - referred to https://github.com/FlipsideCrypto/axelar-models/blob/main/models/descriptions/__overview__.md
> add doc overview page

- models/silver/silver__transactions.sql
Remove temporary null values for an inner CTE. No longer necessary after new columns have been added.
> remove temp null val for new columns

- models/silver/nfts/silver__nft_sales_tensorswap.yml
Per Tensorswap, there can be situations where the owner = seller, where  a user sells into their own pool. This adjusts the unique_combination test to not alert when this occurs in a transactions.
> adjust unique test

- models/silver/nfts/silver__nft_sales_opensea.sql
- models/silver/nfts/silver__nft_sales_opensea.yml
Halting the incremental for Opensea since it recently stopped support for NFTs on Solana.
> stop opensea incremental

- models/silver/liquidity_pool/silver__liquidity_pool_events_orca.sql
- models/silver/liquidity_pool/silver__liquidity_pool_events_raydium.sql
snowflake no longer support flatten's with an on statement.
000002 (0A000): Unsupported feature 'lateral table function called with OUTER JOIN syntax or a join predicate (ON clause)'
What actions do you need to take? 
For the best possible experience and to avoid any failure, we suggest rewriting your queries if they contain the ON clause for a lateral table function (other than SQL UDTFs) or an outer lateral join to a table function (other than SQL UDTF) as suggested below:
Change outer joins with non-SQL table function on the nullable side (right side of a LEFT JOIN, left side of a RIGHT JOIN, or either side of a FULL JOIN) to cross joins (for example, if the current query says LEFT JOIN change it to say JOIN or better, a comma)
Move ON clauses to WHERE filters
> AN-3554 fixes for snowflake changes

- macros/bronze_api/get_helius_compressed_nft.sql
- decrease limit to 500 as some call's exceed the livequery size limit
- increase limit for final page
> adjust limit in cNFT macros

- models/streamline/parser/history/streamline__all_undecoded_instructions_history.sql
- Limit the max range of blocks streamline is given work for on any given run
- This is done to limit impact on downstream incremental loads. If the distribution of blocks in a given instance is wide, it will force a large scan of the bronze data and cause performance issues on incremental. By limiting the block range here, we are able to force it to only load a max of a few partitions at a time since we are partitioning every 100,000 blocks
- Tested [here](https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01af4b6d-0603-cac7-3d4f-830165e35943/detail?autoRefreshInSeconds=0) w/ 5M records loaded by the historical model
> reduce max block range filtered per run

- models/silver/_observability/silver_observability__transactions_completeness.sql
- Will also need to run a one-time script to hot-swap the tables because of changing the column type.
`use role DBT_CLOUD_SOLANA;
create or replace TRANSIENT TABLE solana.silver_observability.TRANSACTIONS_COMPLETENESS_2 (
TEST_NAME VARCHAR(12) COMMENT 'Name for the test',
MIN_BLOCK NUMBER(38,0) COMMENT 'The lowest block id in the test',
MAX_BLOCK NUMBER(38,0) COMMENT 'The highest block id in the test',
MIN_BLOCK_TIMESTAMP TIMESTAMP_NTZ(9) COMMENT 'The lowest block timestamp in the test',
MAX_BLOCK_TIMESTAMP TIMESTAMP_NTZ(9) COMMENT 'The highest block timestamp in the test',
BLOCKS_TESTED NUMBER(18,0) COMMENT 'Count of blocks in the test',
BLOCKS_IMPACTED_COUNT NUMBER(18,0) COMMENT 'Count of block gaps in the test',
BLOCKS_IMPACTED_ARRAY ARRAY COMMENT 'Array of affected blocks', …
> change data type by using sysdate

- models/silver/metadata/silver__solscan_tokens.yml
Once we figure out whether we will continue using Solscan via paid version we can revert this
> temp change while we resolve solscan api issue

- .github/workflows/dbt_run_helius_metadata.yml
- models/bronze/bronze_api/bronze_api__helius_nft_metadata.sql
**Problem**
For whatever reason, somewhere between 50 and 100 calls to the livequery external func causes the query to hang on the Snowflake side. I tested this by breaking the batch of 100 into 2 batches of 50. When I did this, both batches (1-50, 51-100) finished in ~1.5mins. When I combined them into 1 statement (1-100), the query hangs (i.e. It never even sends the request to livequery API). I confirmed this behavior by looking at the livequery logs, as I see 2 sets of 50 logs messages that call the API but when I run the full 100, there are 0 logs in Cloudwatch.
**Fixes**
- Change bronze api model to only run 50 requests
- Change workflow job to run the bronze api model twice so we still get 100 responses per workflow invocation
- Modify the for loop range() such that it will output …
> break up the model to only run 50 requests per invocation

- .github/workflows/dbt_run_helius_metadata.yml
- models/bronze/bronze_api/bronze_api__helius_nft_metadata.yml
- Helius backfill has caught up so adjusting the run interval
- Running it twice a day, based on the assumption this table doesn't have to be updated too frequently. 
- The nft_mints table averages about 15k mints every 1/2 day, and the current job should get about 20k mints per run, so there's a decent buffer. If it does get backed up the test on the bronze_api__helius_nft_metadata should alert
> update frequency and add test

- models/bronze/bronze__blocks.sql
- models/bronze/bronze__transactions.sql
disable `bronze.blocks` and `bronze.transactions` since they have been replaced with `blocks2` and `transactions2` a while ago
> disable old bronze

- models/bronze/bronze_api/bronze_api__solscan_blocks.sql
- Do not make external function call when there are no `block_ids` returned from the base CTE
> do not call udf if no block ids

- .github/workflows/dbt_run_get_nft_compressed_backfill.yml
- data/github_actions__workflows.csv
- macros/streamline/bulk_parse_compressed_nft_mints/udf_bulk_parse_compressed_nft_mints.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- Add `max_batch_rows` to force snowflake to make a separate external function call per row of data
- Change producer model to return 10 rows of data
- each row is aggregated to 1000 instructions
- Change schedule to call the workflow less but increase the number of producer calls per workflow
- This will 50x our throughput vs. current
> An 4090/force paralell execution

- models/silver/nfts/silver__nft_compressed_mints_onchain.sql
- Fix issue where non-mint bubblegum event was being included in the model
- This is due to more than one bubblegum event being in a single transaction and one of them is a mint and one is not
- Check the accounts size to determine whether to include
- tx_id of interest `3SPTg1N6qKqHUtNEJpVYHgcSKoc1doJF8Y6W8A1dtJPLkrnAYG2HkUJqUcybhJvc39FsfRTFvB59pnXJb7FLLbDc`
> exclude instructions that dont have enough accounts

- models/silver/rewards/silver__rewards_fee.sql
- models/silver/rewards/silver__rewards_fee.yml
- models/silver/rewards/silver__rewards_rent.yml
- models/silver/rewards/silver__rewards_staking.sql
- models/silver/rewards/silver__rewards_staking.yml
- models/silver/rewards/silver__rewards_voting.sql
- models/silver/rewards/silver__rewards_voting.yml
- add non_core tag to rewards to initiate incremental runs. Did not include `rewards_rent` since it was recently removed as a part of block rewards in Solana
- add filter to null block_timestamp test
> rewards incremental and update test

- models/silver/swaps/silver__swaps_intermediate_jupiterv6.sql
- Add buffer lookback on `max(_inserted_timestamp)` due to time difference between when records are inserted into `transfers` and when events are decoded in `decoded_instructions` 
- 1 day for `transfers` and 1 hour for `decoded_instructions`
> add buffered lookback

- models/silver/metadata/silver__nft_collection.yml
The recency test using _inserted_timestamp gives false alerts, since the data is being correctly ingested albeit backed up due to large NFT volume. This change will now confirm that the process is working correctly -- the to-do is to look into ways to adjust the logic to account for larger rises in volume.
> use inserted_timestamp for recency test

- macros/helpers/decoded_instructions_backfill_helpers.sql
- Fix performance issue caused by mistakenly using `UNION`. `UNION ALL` should be used instead
- Fix issue with inner_instructions query using wrong program_id value
- This was causing the views to not return results when it should
> use union all instead of union, fix inner_instruct backfill cte

- models/silver/parser/silver__decoded_instructions.sql
- Use a 2 hour lookback to prevent missing decoded instructions due to inner join with blocks table
- In current state, if block for a decoded instruction has not been ingested then the decoded instruction will never get loaded into the table
> 2 hour look back

- tests/test_silver__decoded_instructions_missing.sql
- Check `silver.decoded_instructions` for records in bronze that did not make it into silver with 1 day lag
- This was an issue with previous model logic since it was using an inner join w/ `silver.blocks`. There is now a 2 hour look back to check for late arriving data, but missing data would still happen if things fall out of that window
> add test to check for missing decoded instructs in silver

- dbt_project.yml
- macros/helpers/decoded_instructions_backfill_helpers.sql
- Macro to generate a view to output retry/missing decoder events from previous decoder to run with new decoder
- Generates a view by program_id
- Add default config values for livequery to fix issue when running dbt with non-standard profiles (i.e. dev-2xl, prod-2xl, etc)
> An 4390/retry views for failed old decoder txs

- models/silver/nfts/silver__nft_compressed_mints.sql
Fixing error from [https://github.com/FlipsideCrypto/solana-models/actions/runs/7536313920/job/20513554807](https://github.com/FlipsideCrypto/solana-models/actions/runs/7536313920/job/20513554807)
I reran the incremental in prod w/ this fix applied and it worked
> 15:02:44  Concurrency: 8 threads (target='prod')
> 15:02:44  
> 15:02:44  1 of 1 START sql incremental model silver.nft_compressed_mints ................. [RUN]
> 15:03:28  1 of 1 OK created sql incremental model silver.nft_compressed_mints ............ [SUCCESS 2966407 in 44.02s]
> add alias to prevent ambiguous col name

- models/silver/prices/silver__token_prices_coin_gecko_hourly.sql
- bug fix: when tokens have the same `symbol`, the imputed price may be set incorrectly. The field `id` is added to the partition by.
- example of incorrect prices when tokens have same symbol 'btc' :
```
SELECT
*
FROM solana.silver.token_prices_coin_gecko_hourly
WHERE recorded_hour between '2024-01-13' AND '2024-01-15'
AND symbol = 'btc'
ORDER BY recorded_hour
```
> add extra field for partition

- models/silver/nfts/silver__nft_compressed_mints_onchain.sql
- Include `MintV1` compressed mints in our onchain table
- Backfill of the downstream mints table will be done separately as it requires bronze-api calls
> include mintv1 in onchain table

- models/streamline/decode_instructions/streamline__decode_instructions_2_pyth_realtime.sql
- Reduce worker batch size based on execution results I am seeing in CW logs
- Basically this will result in running 2 lambdas concurrently instead of 1 lambda at current execution intervals
> adjust worker size

- macros/create_udfs.sql
- macros/streamline/streamline_udfs.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- models/streamline/decode_instructions/streamline__idls_nft_compression.sql
- Add udf to new api endpoint
- Add placeholder table to handle grabbing IDLs that is not part of the regular decoding workflow
- This will require some additional ad-hoc setup to get the proper IDL into the table in prod (this is already done in DEV)
- Adjust number of events being parsed in a single call
- Remove events that we know are not change log events that were previously being passed in
> An 4384/new compressed nft endpoint

- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- There is some blackbox issue where the returned UDF results work as expected but when it is followed by order by statement in the create tmp table step for incremental loading it doesnt work. 
- Workaround is to materialize the UDF results in a separate tmp table and then the order by (clustering) operation will work.
```
15:44:44  1 of 1 START sql incremental model bronze_api.parse_compressed_nft_mints ....... [RUN]
15:45:21  1 of 1 OK created sql incremental model bronze_api.parse_compressed_nft_mints .. [SUCCESS 11 in 36.59s]
```
> workaround for materializing  with udf followed by order by cluster key

- macros/streamline/streamline_udfs.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- Force max batch size in UDF
- This was causing some calls to pass multiple rows into the lambda instead of just one batch of requests. The lambda is currently only expecting 1 batch per call
- Decrease batch size
- Saw some instances of longer running execution times, going to reduce it to give it more buffer
- Revert temp fix
> revert patch fix, force udf max batch rows, decrease batch size

- models/silver/parser/silver__decoded_instructions.sql
- Fix issue with race condition where late arriving files with a `_insert_timestamp < max_inserted_timestamp` will not get loaded into silver
- Add a 5 minute look back
- Below is an example scenario I found
```
18:02:04 (start incremental)
18:02:15 (file created not yet registered)
18:03:26 (file registered)
incremental loads max timestamp of 18:02:18
next incremental will miss the late arriving file
```
> lookback 5 minutes to pick up late arriving files

- macros/dbt/get_merge.sql
- macros/helpers/dynamic_block_date_ranges.sql
- macros/helpers/dynamic_range_predicate.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/silver/parser/silver__decoded_instructions_combined.sql
- Refactor the dynamic predicates macro
- Add input params for source and predicate column name
- Only supports INTEGER or DATE data types for predicate column
- Modify existing usages to use this version of the macro
- This will move to `fsc-utils` in the future
> An 4501/generalize dynamic predicate

- models/silver/idls/silver__verified_user_idls.sql
- Fix issue with updated + valid IDLs with an already valid existing IDL not being updated into the table
- Issue was with alias `is_valid` being same name as the column in the existing table. When it references the value in the where clause it is using the wrong one
- Rename alias to something different so it references the value we want not the existing value
> change alias so it selects column we want

- tests/test_streamline__complete_decoded_instructions_2__missing.sql
- Remove the upper bound when searching for completed, the range was too strict and it kept failing even though the data was in completed. 
- This will now pass as long as the data recorded in bronze from 3 hours ago has made it to completed at **any** point in the last 3 hours.
> remove upperbound when searching for completed, too strict

- macros/helpers/decoded_instructions_backfill_helpers.sql
- New helper macro for retrying error events
- Typical use case would be to backfill decodings after an IDL has been updated 
Example usage:
```
dbt run-operation decoded_instructions_backfill_retries_generate_views --args '{"program_id": "JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4", "start_date": "2024-02-02", "end_date": "2024-02-17"}'
```
> An 4546/allow parameterized retries for decoder errs

- models/bronze/bronze_api/bronze_api__solscan_blocks.sql
- Get solscan blocks from list of blocks where they are not in both votes and transactions. These will include blocks that legitimately have 0 txs but will also surface any we are completely missing once we backfill and do a comparison
> get solscan block counts for all potentially completely missing

- tests/test_silver__transactions_missing_partitions.sql
- Missing partitions won't get loaded again since we replaced the data by re-ingesting via new partitions so this test will keep failing
- Solution: basically start the test at a new point in time as we consider the previous partitions fully reconciled
```
15:22:47  1 of 1 START test test_silver__transactions_missing_partitions ................. [RUN]
15:23:15  1 of 1 PASS test_silver__transactions_missing_partitions ....................... [PASS in 27.53s]
```
> adjust missing parts tests

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
- Some programs have inner instruction args that can't be decoded so we should not send them if we can identify them in SQL
- [Examples](https://solscan.io/tx/pMEYwMvGx9Ek3ZeSUckTxs12jHnyZBfjifcYjaz16BRHig129T8jJA7MrcQcKcng5BfepFUCYCKbSWGfSo9k7zH)
- `index=2,inner_index=4`
- `indes=2,inner_index=8`
- The current decoder implementation will output a decoded instruction like `{accounts: null, name: null...}`. Soon a decoder update release will output these as errors. By not sending these anymore we can prevent the error testing from falsely alerting
> only send inner instrs if the account list is >1 for some programs

- models/streamline/decode_instructions/streamline__decode_instructions_2_pyth_realtime.sql
- @eric-laurello and I discovered that dynamic pruning was no longer happening via subquery on `complete_decoded_instructions_2` as of about a week ago. This is causing run time performance degradation.
- To fix, get the min block in a pre-model query and then use it in the model
> fix issue with subquery pruning not happening

- models/silver/bridges/silver__bridge_debridge_transfers.yml
Some records in `silver.transfers` have `null` mints, but the issue is only around unsuccessful txs
> debridge - check succeeded for nulls

- models/silver/parser/silver__decoded_instructions.yml
- Add lookback of 7 days to ensure all data in `decoded` makes it into the `combined` table as we have seen issues where data is missing in the `combined` table
> add test to ensure all data in decoded makes it into the combined table

- models/bronze/labels/bronze__labels.sql
- models/gold/defi/defi__fact_swaps.sql
- fix duplicate` _log_id`s by concatenating the program. Some silver tables aggregate swaps in a tx while others return individual swaps, so duplicates `log_id` can exist
- select modified_timestamp in bronze, so that the silver table inserts only new records
> An 4732/swap duplicates

- models/silver/silver___blocks_tx_count.sql
- Solscan bronze data had an [instance](https://github.com/FlipsideCrypto/solana-models/actions/runs/8706745527/job/23880062549) where it duplicated the same batch of requests and the silver model failed because it was not deduping
- I re-ran the model w/ qualify and it was successful
```
14:05:31  1 of 1 OK created sql incremental model silver._blocks_tx_count ................ [SUCCESS 10726 in 5.43s]
```
> add qualify to dedupe bronze data

- .github/workflows/dbt_run_nft_compressed_mints_realtime.yml
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- models/silver/nfts/silver__nft_compressed_mints_onchain.sql
- Add CTE to filter out transactions that have already run through the compressed mints decoder
- Add onchain mint events for `F9SixdqdmEBP5kprp2gZPZNeMmfHJRCTMFjN22dx3akf` because it uses bubblegum
- Add txs from additional program `F9SixdqdmEBP5kprp2gZPZNeMmfHJRCTMFjN22dx3akf` to be decoded
- Increase workflow job calls by 2
> An 4746/fix c nft parsing

- models/silver/silver__events.sql
SO on `block_id` not working. Giving error `ambiguous column name 'BLOCK_ID'`. Dropping and re-adding was unsuccessfuly. The decision was made to remove it from SO as the explain plan seems to do fine w/o it for block point-lookups.
```
explain 
select *
from solana.silver.events 
where block_id = 178298940;
```
> remove block_id from SO, it is not working on SF due to black box error

- models/silver/parser/silver__decoded_instructions_combined.yml
- models/silver/swaps/silver__swaps_intermediate_meteora.sql
- Use `block_timestamp::date` dynamic predicate
- Use `between_stmts` for pruning `transfers` CTE
- Fix formatting
- Add relationship test between `decoded_instructions_combined` and `swaps_intermediate_meteora`
- **temporarily** remove model from scheduler so I can backfill then re-enable
```
-- full refresh on M
15:10:25  1 of 1 OK created sql incremental model silver.swaps_intermediate_meteora ...... [SUCCESS 1 in 3144.92s]
-- incremental
16:03:31  1 of 1 OK created sql incremental model silver.swaps_intermediate_meteora ...... [SUCCESS 31459 in 18.54s]
-- relationship test
15:40:52  2 of 14 PASS dbt_utils_relationships_where_silver__decoded_instructions_combined_meteora_swaps_tx_id  [PASS in 5.55s]
```
```
-- sample tx fixed compared to current
select 'fixed', tx_id, swap_index, …
```
> An 4786/fix meteora swaps incremental

- models/silver/swaps/silver__swaps_intermediate_jupiterv6.yml
- Add a recent date test filter for jupiter tests
- There are 10 records with NULL `from_mint` and `from_amt` that are going to be ignored because the transaction does not match the account details for whatever reason (ie. jupiter says we are swapping from USDC, but the transfers are USDT)
- [example](https://solscan.io/tx/4bsU1ex4Q3DuFgfikF93reWhL2FU3Mgx3w6SAhPsx44b976Js5LSgVYNeZPBubYfMbntSZmsNWo3cwBw4TAp6sV)
- We don't need to test old records over and over
> add recent date filter for tests

- models/silver/parser/silver__decoded_instructions_combined.yml
- models/silver/swaps/silver__swaps_intermediate_bonkswap.sql
- Use block_timestamp::date dynamic predicate
- Use between_stmts for pruning transfers CTE
- Fix formatting
- Add relationship test between decoded_instructions_combined and swaps_intermediate_bonkswap
- temporarily remove model from scheduler so I can backfill then re-enable
```
-- full refresh on 2xl
13:31:56  1 of 1 OK created sql incremental model silver.swaps_intermediate_bonkswap ..... [SUCCESS 1 in 108.12s]
-- rest of the data via incremental on 2xl
13:54:31  1 of 1 OK created sql incremental model silver.swaps_intermediate_bonkswap ..... [SUCCESS 1 in 206.81s]
-- relationship test runs
14:50:51  2 of 16 PASS dbt_utils_relationships_where_silver__decoded_instructions_combined_swaps_intermediate_bonkswap_tx_id  [PASS in 1.95s]
```
> An 4786/fix bonkswap incremental

- models/silver/parser/silver__decoded_instructions_combined.yml
- models/silver/swaps/silver__swaps_intermediate_dooar.sql
- Use block_timestamp::date dynamic predicate
- Use between_stmts for pruning transfers CTE
- Fix formatting
- Add relationship test between decoded_instructions_combined and swaps_intermediate_bonkswap
- temporarily remove model from scheduler so I can backfill then re-enable
```
-- full refresh on M
17:16:30  1 of 1 OK created sql incremental model silver.swaps_intermediate_dooar ........ [SUCCESS 1 in 2280.36s]
-- incremental on M
14:02:26  1 of 1 OK created sql incremental model silver.swaps_intermediate_dooar ........ [SUCCESS 572 in 20.18s]
-- relationship test runs
13:59:07  2 of 16 PASS dbt_utils_relationships_where_silver__decoded_instructions_combined_swaps_intermedia_dooar_tx_id  [PASS in 3.24s]
```
> An 4786/fix dooarswap incremental

- models/silver/nfts/silver__nft_sales_solanart.yml
- Solanart hasnt seen a sale in a few days, but there's still some listing/delisting activity
- change recency test to 14 days and if no events then we can deprecate
> increase Solanart recency test to 14 days

- .github/workflows/dbt_test.yml
- .github/workflows/dbt_test_hourly.yml
- tests/test_silver__blocks_tx_count_missing_7_days.sql
- tests/test_silver__transactions_and_votes_missing_7_days.sql
- tests/test_silver__transactions_partial_partitions.sql
- tests/test_streamline__complete_decoded_instructions_2__missing.sql
- Add tags for hourly tests
- Exclude hourly tests from daily test workflow
- Use tag in workflow to run hourly tests
```
(dbt-env) dbt test -s tag:test_hourly -t prod
14:16:06  1 of 4 PASS test_silver__blocks_tx_count_missing_7_days ........................ [PASS in 2.98s]
14:16:18  4 of 4 PASS test_streamline__complete_decoded_instructions_2__missing .......... [PASS in 15.00s]
14:16:44  2 of 4 PASS test_silver__transactions_and_votes_missing_7_days ................. [PASS in 40.74s]
14:17:10  3 of 4 PASS test_silver__transactions_partial_partitions ....................... [PASS in 66.28s]
14:17:10  Finished running 4 tests, 11 hooks in 0 hours 1 minutes and 18.30 seconds (78.30s).
14:17:10  
14:17:10  Completed successfully
14:17:10  
14:17:10  Done. PASS=4 WARN=0 ERROR=0 SKIP=0 …
```
> Tag hourly tests

- macros/helpers/decoded_instructions_backfill_helpers.sql
- Reduce decoder backfill size per execution
- The existing limits are no longer accurate due to the addition of `decoded_instructions_combined` which requires a join to `transactions`
- non-core runs will still take longer but will stay under threshold of 30mins
- This size was tested and comparison can be seen below
```
-- backfill causing long run time on decoded_instructions_combined
02:47:37  115 of 137 OK created sql incremental model silver.decoded_instructions_combined  [SUCCESS 100217842 in 2059.64s]
```
```
-- run time after size was reduced
14:20:12  46 of 137 OK created sql incremental model silver.decoded_instructions_combined  [SUCCESS 9600543 in 839.00s]
```
```
-- run time when no large backfill active
11:08:56  44 of 137 OK created sql incremental model …
```
> reduce size per execution

- models/silver/nfts/silver__nft_sales_tensorswap_cnft.sql
- Add one hour look back to avoid issues related to long-running upstream jobs
```
-- incremental on M
14:54:50  1 of 1 OK created sql incremental model silver.nft_sales_tensorswap_cnft ....... [SUCCESS 224689 in 131.62s]
```
> add 1 hour lookback

- tests/test_silver__transactions_missing_partitions.sql
- Move marker up for missing parts test
- There were partitions not loaded to silver likely due to issue w/ long run times in non-core job/overlapping w/ core jobs
- Confirmed this was resolved automatically in new partitions
- Solscan block tx count tests are passing
- Manually checked that the blocks in these partitions were loaded later on (see query below)
```
with was_missing as (
select distinct block_id
from solana.bronze.transactions2
where _partition_id in (80692, 81886)
and error is null
)
, has_counts as (
select m.*, 
count_if(t.block_id is not null) count_txs, 
count_if(v.block_id is not null) count_votes,
from was_missing m
left outer join solana.silver.transactions t 
on m.block_id = t.block_id
left outer join solana.silver.votes v
on m.block_id = v.block_id
group by 1
) …
```
> move marker for test, confirmed OK via other tests/manual check

- models/silver/parser/silver__decoded_instructions_combined.yml
Add a buffer so we don't get false positives from relationship tests where downstream tables are updating at time of test run
```
(dbt-env) dbt test -s models/silver/parser/silver__decoded_instructions_combined.sql -t prod --exclude tag:test_weekly
15:35:18  Finished running 18 tests, 11 hooks in 0 hours 1 minutes and 45.06 seconds (105.06s).
15:35:18  
15:35:18  Completed successfully
15:35:18  
15:35:18  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
> add buffer for relationship tests to avoid false positives

- .github/workflows/dbt_run_decode_instructions.yml
- models/streamline/decode_instructions/streamline__decode_logs_realtime.sql
- Add real-time decoding workflow for jupv6 logs
```
16:20:10  Running macro `if_data_call_function`: Calling udf {{this.schema}}.udf_bulk_instructions_decoder(object_construct('sql_source', '{{this.identifier}}', 'external_table', 'decoded_instructions_2', 'sql_limit', {{var('sql_limit','5000000')}}, 'producer_batch_size', {{var('producer_batch_size','2000000')}}, 'worker_batch_size', {{var('worker_batch_size','100000')}}, 'batch_call_limit', {{var('batch_call_limit','1000')}}, 'call_type', 'logs')) on {{this.schema}}.{{this.identifier}}
16:21:04  1 of 1 OK created sql table model streamline.decode_logs_realtime .............. [SUCCESS 1 in 53.95s]
```
```
select *
from solana_dev.bronze.streamline_decoded_instructions_2
where _inserted_timestamp >= '2024-05-21'
limit 100;
```
> Jupv6 logs decoding

- models/silver/swaps/silver__swaps_intermediate_jupiterv6.sql
- Patch fix issue with multiple jupiter agg swap calls within a single instruction
- Only output the 1st set of swaps in cases jupiter is called by a wrapper program
We currently have 4 instances of this happening, the qualify statement will remove these
```
-- count of jupiter swaps to be added to model before change
1035125
-- count after
1035120
```
Affected records now only output 1 row
> take the first set if multiple inner swaps use jup agg

- models/silver/silver___post_token_balances.sql
- models/silver/silver___post_token_balances.yml
- models/silver/silver___pre_token_balances.sql
- models/silver/silver___pre_token_balances.yml
Add succeeded column to _pre_token_balances and _post_token_balances
- no impact on models referencing these tables
- will use ad-hoc query in SF to update historical records after column is added - ie:
```
UPDATE solana.silver._pre_token_balances a
SET a.succeeded = b.succeeded
FROM (
Select tx_id,succeeded from solana.silver.transactions
where block_timestamp::date = '2024-01-06'
) as b
WHERE a.tx_id = b.tx_id
and a.block_timestamp::date = '2024-01-06';
```
> add succeeded column

- .github/workflows/dbt_run_decode_instructions.yml
- Remove the current logs decoding path from workflows. Will be replaced soon w/ new pipeline
statement to remove decoded logs data from `decoded_instructions` and `decoded_instructions_combined`. Data is currently unused and will be re-decoded as we backfill using new pipeline
```
delete from solana.silver.decoded_instructions_combined
where program_id = 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
and event_type = 'SwapEvent';
delete from solana.silver.decoded_instructions
where program_id = 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4'
and decoded_instruction:name::string = 'SwapEvent';
```
> remove logs from workflow

- macros/create_udfs.sql
- macros/python/udfs.sql
- models/silver/program_logs/silver__transaction_logs_program_data.sql
- models/silver/program_logs/silver__transaction_logs_program_data.yml
- Create UDF to get program data messages from log messages
- Add table to output encoded program data that is stored in the tx log messages
- TXs with no such logs are excluded
- Only successful txs
- This will be used by streamline models for decoding logs
- Purposely no schedule at this time
```
-- full refresh on M (1 day's worth of data)
14:33:25  1 of 1 OK created sql incremental model silver.transaction_logs_program_data ... [SUCCESS 1 in 111.63s]
-- incremental on M
14:42:36  1 of 15 OK created sql incremental model silver.transaction_logs_program_data .. [SUCCESS 5069080 in 48.27s]
-- tests pass on dev (except recency as expected)
14:49:08  Done. PASS=14 WARN=0 ERROR=1 SKIP=0 TOTAL=15
```
> Encoded program data logs table

- models/silver/swaps/silver__swaps_intermediate_jupiterv6.yml
- Temporarily turn these off while we work on logs decoding + model refactor. Low impact as these usually have to do with "odd" txs and affect < 10 txs
> tmp turn off null checks for to/from cols

- macros/python/udfs.sql
- models/silver/program_logs/silver__transaction_logs_program_data.sql
- models/silver/program_logs/silver__transaction_logs_program_data.yml
- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
- Handle additional log extraction edge cases
- Handle logs that end in `" success"` but are not actually program log end
- Handle logs being truncated as last message
- Handle logs being truncated but additional messages are rendered before it ends
- Handle legacy BPG program log format
- Ignore txs with `NULL` log_messages in model
- Add `_udf_error` column to schema
- Fix missing doc ref comment for logs realtime query
> Add b58 decoding to logs extraction udf

- .github/workflows/dbt_run_decode_logs_backfill.yml
- .github/workflows/dbt_run_decode_logs_orchestrator.yml
- macros/helpers/decoded_logs_backfill_helpers.sql
- models/streamline/decode_logs/streamline__complete_decoded_logs_backfill.sql
- Add decoded logs backfill helper macros
- Add decoded logs backfill workflow
- Add to orchestrator
- Add model to store completed views
Call in dev to decode 20M records
```
(dbt-env) dbt run-operation decoded_logs_backfill_calls --vars '{"STREAMLINE_INVOKE_STREAMS": True}' -t dev
15:56:10  Running with dbt=1.7.4
15:56:11  Registered adapter: snowflake=1.7.0
15:56:11  Unable to do partial parsing because config vars, config profile, or config target have changed
15:56:20  Found 336 models, 1948 tests, 49 seeds, 11 operations, 5 analyses, 68 sources, 0 exposures, 0 metrics, 1087 macros, 0 groups, 0 semantic models
15:56:22  Running macro `if_data_call_function`: Calling udf STREAMLINE.udf_bulk_instructions_decoder(object_construct('sql_source', …
```
> Streamline decoded logs backfill

- models/silver/validator/silver__snapshot_block_production.yml
- models/silver/validator/silver__snapshot_stake_accounts.yml
- models/silver/validator/silver__snapshot_validators_app_data.yml
- models/silver/validator/silver__snapshot_vote_accounts.yml
- models/silver/validator/silver__snapshot_vote_accounts_extended_stats.yml
add recency test on `_inserted_timestamp` for validator tables
- data should be inserted for these models around 0 UTC daily via `dbt_run_daily` (except for block_production), so timing it with `dbt_test` run at 9am UTC
- 12 hr test for `vote_accounts` + `stake_accounts` + `validators_app_data` - expect new records from latest run
- 2 day test for `snapshot_vote_accounts_extended_stats` + `snapshot_block_production`
> add recency tests

- macros/helpers/decoded_logs_backfill_helpers.sql
- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
- Modify realtime and backfill queries so that jupiterv6 swaps initiated by a different program than jupiterv6 are still sent for decoding
- Decrease backfill step size
> request log decode for jup6 swaps called by a diff program than jup6

- models/silver/metadata/silver__decoded_metadata.sql
- models/silver/metadata/silver__decoded_metadata.yml
- models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql
- Create `silver__decoded_metadata` table containing decimal and available metadata for tokens
- [design diagram](https://www.figma.com/board/HmO4271WUo9ZBxII13m1vO/native_metadata?node-id=0-1&t=2Oq12j3IyszMgilt-0)
- update `silver__swaps_inner_intermediate_jupiterv6` to use new table = now runs in 1/3rd of the time
- existing model runtime: `[SUCCESS 339299 in 180.25s]`
- updated model runtime: `[SUCCESS 339299 in 53.32s]`
```
Full test (without recency filters)
Finished running 5 tests, 11 hooks in 0 hours 0 minutes and 19.05 seconds (19.05s). 
Completed successfully 
Done. PASS=5 WARN=0 ERROR=0 SKIP=0 TOTAL=5
Incremental
1 of 1 OK created sql incremental model silver.decoded_metadata ................ [SUCCESS 6250 in 12.73s]
FR on 2xl
1 of 1 OK created sql incremental model …
```
> decoded metadata and update inner jup swaps model

- macros/helpers/decoded_logs_backfill_helpers.sql
- Based on testing at scale in dev, the phoenix log decoding backfill takes longer to run per instruction so we need to spread the work across more workers
- This is expected. We basically have to run the decoder twice per instruction (one time to get the # of fields in args since it's dynamic, then a second time to do the actual decoding)
- Sample [log](https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fsolana-api-dev-WorkerLogsDecoderBackfill-jeB7VB9ug0tQ/log-events/2024$252F07$252F12$252F$255B$2524LATEST$255D027b4e25b4d44ecc8398511364a77967) with the updated values
- This is a temporary change and we can revert back to original values once the backfill is doen
> spread work across more workers

- models/silver/silver__blocks.sql
- Use generated static timestamp/date values for query pruning in incremental logic
- Tested by compiling with `-t prod` so that it looks at the realtime streamline data
`dbt compile -s models/silver/silver__blocks.sql -t prod` 
- Took the output and ran it in snowflake
> refactor incremental to use dynamically generated string literals for pruning

- models/silver/parser/silver__decoded_logs.sql
- Use new metadata for column values so we don't have to do joins to `silver.blocks` or `silver.transactions`
- This will improve performance overall but specifically backfill performance when we have to do larger lookbacks
- This is backwards compatible in case there is a need to re-run the model for older dates
- I spoofed the cutover date to test the backwards compatibility
- [Query](https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01b5bb03-0506-9dc0-3d4f-83023c3a680b/detail?autoRefreshInSeconds=0) that creates the tmp table query to get `between_stmts` 
- [Query](https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01b5bb03-0506-8b9f-3d4f-83023c3a5b7f/detail?autoRefreshInSeconds=0) running old model logic that uses join to `silver.transactions`
``` …
```
> refactor logic to use new passthrough data, make backwards compatible

- models/silver/silver__transactions.yml
- Add `silver.transactions` test for `null` instructions 
- Add `silver.transactions` test for `null` inner_instructions 
Tests added to identify potential issues with raw data. This hasn't occurred since 2022 so it feels like overkill to add this to "self-healing" streamline requests as the addition would add some substantial run time to the existing process. 
```
15:25:10  5 of 14 PASS not_null_silver__transactions_INNER_INSTRUCTIONS .................. [PASS in 115.66s]
15:25:46  6 of 14 PASS not_null_silver__transactions_INSTRUCTIONS ........................ [PASS in 151.16s]
```
> add test for missing instructions/inner_instructions

- models/silver/balances/silver__token_balances.yml
- models/silver/program_logs/silver__transaction_logs_program_data.yml
- models/silver/stats/silver__core_metrics_hourly.yml
- Ignore older block timestamps for certain tests that started failing due to backfill of blocks that were missing inner_instructions data
`dbt test -s silver__core_metrics_hourly.sql silver__token_balances silver__transaction_logs_program_data -t prod`
```
14:40:15  Finished running 53 tests, 11 hooks in 0 hours 6 minutes and 10.01 seconds (370.01s).
14:40:15  
14:40:15  Completed successfully
14:40:15  
14:40:15  Done. PASS=53 WARN=0 ERROR=0 SKIP=0 TOTAL=53
```
> adjust dates for some tests for older txs

- models/silver/silver__transactions.sql
- Modify `silver.transactions` logic to handle txs that could have non-vote/non-compute instructions within a vote transaction
To reconcile I ran a few partitions through both the existing and new model logic. These vote txs with non-vote instructions are rare so the expectation would be for these 2 versions to produce no diffs of the new one to have slightly more (1 to 2 txs). In the real-time samples I tested, they produced no diffs. In the partition where I know one of these existed, they produced the expected diff.
Also there does not seem to be any noticeable performance degradation for runtime (expected 1-2mins)
> Hotfix solana txs votes

- .github/workflows/dbt_test.yml
- Remove this test, the newer solscan blocks tests already cover this and is able to self-recover unlike this test.
> remove the test

- models/streamline/decode_instructions/streamline__decode_instructions_2_realtime.sql
- The `pump_fun`  inner_instructions are actually log `events` and should be sent through the log decoding pipeline. This is to exclude those from the regular instructions pipeline
Ex: This is a `TradeEvent`
> exclude pumpfun logs from decode instruction request

- .github/workflows/dbt_run_streamline_stake_accounts_snapshot.yml
- models/streamline/stake_accounts/streamline__stake_account_states.sql
- models/streamline/stake_accounts/streamline__stake_account_states.yml
- Create a table to hold current stake account state values
- To be used downstream to power streamline requests for account information
To test against prod data...
1. `dbt compile -s streamline__stake_account_states -t prod`
2. Copy the query from `target/compiled/solana_models/models/streamline/stake_accounts/streamline__stake_account_states.sql`
3. Prefix query with `CREATE OR REPLACE TRANSIENT TABLE solana_dev.streamline.stake_account_states_prod AS`
4. Run it in snowflake
5. Get the `max(_inserted_timestamp)` from the current snapshots table
```
select max(_inserted_timestamp) 
from solana.silver.snapshot_stake_accounts;
```
6. Input into this query
```
WITH diffs AS (
select distinct stake_pubkey
from solana.silver.snapshot_stake_accounts
where _inserted_timestamp = '< CURRENT MAX …
```
> Stake account states

- models/silver/validator/silver__snapshot_vote_accounts.yml
When the `authorized_withdrawer = '11111111111111111111111111111111'`, the `authorized_voter` is null, so adjusted test to exclude these
`5 of 16 PASS not_null_silver__snapshot_vote_accounts_authorized_voter .......... [PASS in 2.37s]`
> add filter to null authorized_voter test

- models/streamline/decode_logs/streamline__decode_logs_realtime.sql
Add Pumpfun logs to requests for logs decoder
- DML to remove events from silver.decoded_instructions_combined and silver.decoded_instructions (`withdraw` events are the only ones without 'logs' so excluded those)
```
delete from solana.silver.decoded_instructions_combined
where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
and (event_type <> 'withdraw' or event_type is null)
and inner_index is not null;
delete from solana.silver.decoded_instructions 
where program_id = '6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P'
and (decoded_instruction:name::string <> 'withdraw' or decoded_instruction:error is not null)
and inner_index is not null;
```
- Command to run backfill for last two days
`dbt run-operation decoded_logs_backfill_generate_views --args '{"program_id": …
> add pumpfun to realtime

- models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql
Some amounts are intermittently being set to NULL during decimal adjustment when the mint is not found in `decoded_metadata`. This can happen if a block arrives late in bronze or there is some issue with the modeling upstream. In order to mitigate this issue we can use LiveQuery to query for any missing token decimals and re-apply the decimal adjustment as the final step(s) of the model
You can test now in DEV by doing
```
delete from solana_dev.silver.swaps_inner_intermediate_jupiterv6
where _inserted_timestamp >= '2024-08-12 15:37:15.000';
dbt run -s models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql -t dev
```
Incremental on M
```
15:14:07  1 of 1 OK created sql incremental model silver.swaps_inner_intermediate_jupiterv6  [SUCCESS 2383524 in 91.47s]
```
Tests …
> add CTEs to get decimals via livequery if data is delayed from bronze

- models/gold/gov/gov__fact_stake_accounts.sql
- models/gold/gov/gov__fact_validators.sql
- models/gold/gov/gov__fact_vote_accounts.sql
- models/gold/nft/nft__fact_nft_sales.sql
- models/silver/metadata/helius/silver__helius_nft_metadata.sql
- models/silver/metadata/silver__nft_collection.sql
- models/silver/nfts/silver__nft_burn_actions.sql
- models/silver/nfts/silver__nft_compressed_mints.sql
- models/silver/nfts/silver__nft_mint_actions.sql
- models/silver/nfts/silver__nft_mints.sql
- models/silver/nfts/silver__nft_sales_amm_sell_decoded.sql
- models/silver/nfts/silver__nft_sales_exchange_art.sql
- models/silver/nfts/silver__nft_sales_hadeswap.sql
- models/silver/nfts/silver__nft_sales_hyperspace.sql
- models/silver/nfts/silver__nft_sales_magic_eden_cnft.sql
- models/silver/nfts/silver__nft_sales_magic_eden_v2.sql
- models/silver/nfts/silver__nft_sales_solanart.sql
- models/silver/nfts/silver__nft_sales_solsniper.sql
- models/silver/nfts/silver__nft_sales_solsniper_cnft.sql
- models/silver/nfts/silver__nft_sales_tensorswap.sql
- models/silver/nfts/silver__nft_sales_tensorswap_cnft.sql
- models/silver/silver__staking_lp_actions.sql
- models/silver/silver__staking_lp_actions_labeled.sql
- models/silver/validator/silver__snapshot_stake_accounts.sql
- models/silver/validator/silver__snapshot_validators_app_data.sql
- models/silver/validator/silver__snapshot_vote_accounts.sql
Search optimization and clustering for NFT and GOV schema
1. For larger/complex core views with union/join logic, convert to table and update silver clustering
- add logic to select from legacy views only during FR
- includes: `gov.fact_stake_accounts`, `gov.fact_validators`, `gov.fact_vote_accounts`, `nft.fact_nft_sales`)
3. For views with simpler logic, add SO and clustering to silver references
FR successful for core tables (on 2xl):
```
-- 23:47:48  2 of 5 OK created sql incremental model gov.fact_validators .................... [SUCCESS 1 in 23.25s]
-- 23:47:53  3 of 5 OK created sql incremental model gov.fact_vote_accounts ................. [SUCCESS 1 in 28.33s]
-- 23:48:27  4 of 5 OK created sql incremental model nft.fact_nft_sales ..................... [SUCCESS 1 in 61.76s]
-- …
```
> An 5088/gold optimization 2

- requirements.txt
- Requires separate installation of `dbt-core` and `dbt-snowflake`
- Python required to be >= `v3.11`
To install locally, run below command in your virtual environment
`pip install dbt-core~=1.8 dbt-snowflake~=1.8`
> upgrade to dbt 1.8.x

- models/sources.yml
- models/streamline/streamline__all_unknown_block_rewards_real_time.sql
- tests/test_silver__rewards_gaps.sql
- Test for missing rewards in streamline table. Every block should have at least one reward record
- Identify any missing rewards that are from the first block of an epoch as these should be treated differently on retry
- Auto retry missing rewards
Current state, all missing are non-first epoch blocks
```
13:58:48  1 of 1 FAIL 42663 test_silver__rewards_gaps .................................... [FAIL 42663 in 20.06s]
```
Streamline realtime view successfully built
```
14:21:16  1 of 1 OK created sql view model streamline.all_unknown_block_rewards_real_time  [SUCCESS 1 in 1.84s]
```
> Auto heal block rewards and test

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.yml
- Add DCA related columns
- Flag to indicate whether a swap was initiated by Jupiter DCA
- List the original wallet that requested the DCA if the above is true
- Add tests for new columns
- Will require backfill for new columns once the decoder is fully backfilled for DCA logs. See comments for backfill query
Incremental on M
```
16:29:34  1 of 1 OK created sql incremental model silver.swaps_intermediate_jupiterv6_2 .. [SUCCESS 92451 in 126.06s]
```
Tests pass on dev
```
16:23:32  Finished running 23 data tests, 11 project hooks in 0 hours 0 minutes and 31.92 seconds (31.92s).
16:23:32  
16:23:32  Completed successfully
16:23:32  
16:23:32  Done. PASS=23 WARN=0 ERROR=0 SKIP=0 TOTAL=23
```
> add dca related columns and tests

- tests/test_silver__decoded_logs_jupiter_dca_signers.sql
- Add test to detect if a new DCA signer is used by Jupiter
```
16:45:27  15 of 16 PASS test_silver__decoded_logs_jupiter_dca_signers .................... [PASS in 4.01s]
```
> add test for new dca signers

- models/gold/defi/defi__fact_swaps.sql
- models/gold/defi/defi__fact_swaps.yml
Remove jupv6 swaps from `fact_swaps`, as these now live in separate tables
DML to delete:
```
delete from solana.defi.fact_swaps
where program_id = 'JUP6LkbZbjS1jKKwapdHNy74zcZ3tLUZoi5QNyVTaV4';
```
fact_swaps incremental run in dev:
```
16:56:20  Finished running 1 incremental model, 11 hooks in 0 hours 0 minutes and 52.50 seconds (52.50s).
16:56:20  
16:56:20  Completed successfully
```
> remove jupv6

- models/gold/gov/gov__fact_validators.yml
- models/silver/swaps/generic/silver__swaps_intermediate_generic.yml
- remove recency test from generic swaps
- exclude specific pubkeys from gold validators due to null response from API
tests:
- fact_validators
```
12:06:33  Finished running 37 data tests, 11 project hooks in 0 hours 0 minutes and 38.94 seconds (38.94s).
12:06:33  
12:06:33  Completed successfully
12:06:33  
12:06:33  Done. PASS=37 WARN=0 ERROR=0 SKIP=0 TOTAL=37
```
- silver__swaps_intermediate_generic
```
12:10:01  Finished running 10 data tests, 11 project hooks in 0 hours 2 minutes and 30.67 seconds (150.67s).
12:10:01  
12:10:01  Completed successfully
12:10:01  
12:10:01  Done. PASS=10 WARN=0 ERROR=0 SKIP=0 TOTAL=10
```
> update tests for generic swaps and gold validators

- .github/workflows/dbt_test.yml
- models/silver/validator/silver__snapshot_stake_accounts.sql
- add 'exclude_test_daily' tag for older version of snapshot_stake_accounts
- remove the events_inner tables from the exclusion
> add tag to exclude from test; add back events_inner

- models/gold/gov/gov__fact_rewards_fee.sql
- models/gold/gov/gov__fact_rewards_staking.sql
- models/gold/gov/gov__fact_rewards_voting.sql
- models/silver/rewards/silver__rewards_fee_2.sql
- models/silver/rewards/silver__rewards_fee_2.yml
- models/silver/rewards/silver__rewards_staking_2.sql
- models/silver/rewards/silver__rewards_staking_2.yml
- models/silver/rewards/silver__rewards_voting_2.sql
- models/silver/rewards/silver__rewards_voting_2.yml
- Add v2 models for `rewards_staking`, `rewards_fee`, `rewards_voting`
- Use the v2 models after block `292334107` in downstreams
- Continue running v1 in parallel to do some more reconciliation. Will disable in future PR
```
select rewards_staking_id
from solana.silver.rewards_staking
where block_id > 292334107
and block_id <= 293479759
except 
select rewards_staking_2_id
from solana_dev.silver.rewards_staking_2
where block_id > 292334107
and block_id <= 293479759;
select rewards_fee_id
from solana.silver.rewards_fee
where block_id > 292334107
and block_id <= 293479759
except 
select rewards_fee_2_id
from solana_dev.silver.rewards_fee_2
where block_id > 292334107
and block_id <= 293479759;
select rewards_voting_id
from solana.silver.rewards_voting
where block_id > 292334107
and block_id …
```
> v2 reward fees model

- models/silver/silver__transactions.sql
Get `units_consumed` value from raw transaction data, which is included in the node response after block `204777016`
to-do:
- Backfill will be another PR for separate workflow to create new table with updated `units_consumed` value, and used to update silver table
- For testing, add a null test to column and include 7 day filter -- will add after backfill update is complete since it will raise errors until then
inc run on medium
`17:52:40  1 of 1 OK created sql incremental model silver.transactions .................... [SUCCESS 1226726 in 121.31s]`
no null values returned for run
```
select * from solana_dev.silver.transactions
where _partition_id > 120818 and units_consumed is null;
```
> An 5328/update compute units logic

- .github/workflows/dbt_run_streamline_validator_vote_accounts_snapshot.yml
- models/bronze/streamline/bronze__streamline_FR_validator_vote_accounts_2.sql
- models/bronze/streamline/bronze__streamline_validator_vote_accounts_2.sql
- models/sources.yml
- models/streamline/core/snapshot/streamline__validator_vote_accounts_2.sql
- Add streamline 2.0 pipeline for validator vote accounts data
- This is a snapshot and will run once per day
Requests on M
```
16:50:20  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"exploded_key": "[\"result.current\", \"result.delinquent\"]",
"external_table": "validator_vote_accounts_2",
"producer_batch_size": "1",
"sql_limit": "1",
"worker_batch_size": "1"
}
16:50:28  1 of 1 OK created sql view model streamline.validator_vote_accounts_2 .......... [SUCCESS 1 in 8.10s]
```
Data in dev
```
select *
from solana_dev.bronze.streamline_FR_validator_vote_accounts_2;
```
> Migrate validator vote accounts to streamline 2.0

- .github/workflows/dbt_run_streamline_validator_vote_program_accounts.yml
- models/bronze/streamline/bronze__streamline_FR_validator_vote_program_accounts_2.sql
- models/bronze/streamline/bronze__streamline_validator_vote_program_accounts_2.sql
- models/sources.yml
- models/streamline/core/snapshot/streamline__validator_vote_program_accounts_2.sql
- Add streamline 2.0 pipeline for validator vote program accounts data
- This is a snapshot and will run once per day
Requests on M
```
15:21:08  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"exploded_key": "[\"result.value\"]",
"external_table": "validator_vote_program_accounts_2",
"producer_batch_size": "1",
"sql_limit": "1",
"worker_batch_size": "1"
}
15:21:16  1 of 1 OK created sql view model streamline.validator_vote_program_accounts_2 .. [SUCCESS 1 in 8.37s]
```
Data in dev
```
select *
from solana_dev.bronze.streamline_FR_validator_vote_program_accounts_2;
```
> Migrate validator vote program accounts

- models/silver/silver__blocks.sql
- Add streamline 2.0 raw data upstream to `silver__blocks`
- All data in the model after and including the `295976124` cutoff block will come from the new upstream
Dev is currently setup to run off of prod streamline data. This query should return no results after an incremental run in dev
```
select block_id
from solana.silver.blocks
where block_id >= 295976124
except
select block_id
from solana_dev.silver.blocks
where block_id >= 295976124;
```
Incremental on M
`dbt run -s silver__blocks`
```
16:12:57  1 of 1 OK created sql incremental model silver.blocks .......................... [SUCCESS 1173 in 15.79s]
```
Tests pass
`dbt test -s silver__blocks -t dev --exclude test_silver__token_account_owners_recency`
```
16:12:08  Finished running 10 data tests, 11 project hooks in 0 hours 0 …
```
> use streamline 2.0 raw data

- .github/workflows/dbt_run_streamline_validator_metadata_snapshot.yml
- models/bronze/streamline/bronze__streamline_FR_validator_metadata_2.sql
- models/bronze/streamline/bronze__streamline_validator_metadata_2.sql
- models/sources.yml
- models/streamline/core/snapshot/streamline__validator_metadata_2.sql
- Add streamline 2.0 pipeline for validator metadata
- Old pipeline was through solscan, but that API is dead (it has been for a bit) with no replacement as far as I can tell
- New api is through https://topvalidators.app/ and the only thing "missing" in the data is the `validator_rank`. I found that the ranking is just by the # of active stake in descending order. We can do that downstream to get the ranking value that matches solscan's old API response. You can see the solscan ranking [here](https://solscan.io/validator?page=1)
`dbt run -s streamline__validator_metadata_2 --vars '{"STREAMLINE_INVOKE_STREAMS": True}' -t dev`
```
16:24:24  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"external_table": "validator_metadata_2", …
```
> Migrate validator rank metadata

- .github/workflows/dbt_run_streamline_validator_vote_program_accounts_snapshot.yml
- .github/workflows/dbt_run_streamline_validators_list_snapshot.yml
- models/bronze/streamline/bronze__streamline_FR_validators_list_2.sql
- models/bronze/streamline/bronze__streamline_validators_list_2.sql
- models/sources.yml
- models/streamline/core/snapshot/streamline__validators_list_2.sql
- Migrate validator list requests to streamline 2.0
- Data is unflattened. Streamline 2.0 doesnt seem to be able to flatten when the response is an array w/ no property name. Data is small though, shouldnt be any issues flattening in SF
- Fix workflow naming for streamline validator vote program accounts
`dbt run --vars '{STREAMLINE_INVOKE_STREAMS: True}' -s streamline__validators_list_2`
```
16:54:38  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"external_table": "validators_list_2",
"producer_batch_size": "1",
"sql_limit": "1",
"worker_batch_size": "1"
}
16:54:46  1 of 1 OK created sql view model streamline.validators_list_2 .................. [SUCCESS 1 in …
```
> Migrate validator list to streamline 2.0

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
- Fix a few swaps where it is listed a `is_dca_swap=TRUE` when it should be `FALSE`
- Need to check to make sure DCA program is called in the request as there are some swaps done by the DCA signers that don't appear to be DCA swaps
`dbt run -s silver__swaps_intermediate_jupiterv6_2 -t dev`
```
17:38:49  1 of 1 OK created sql incremental model silver.swaps_intermediate_jupiterv6_2 .. [SUCCESS 273561 in 130.18s]
```
Tests are failing but that is due to model test failures that are currently in production unrelated to this.
DML to update the existing non-dca swaps marked as `is_dca_swap=TRUE`
```
UPDATE solana.silver.swaps_intermediate_jupiterv6_2 AS t
SET
is_dca_swap = FALSE,
modified_timestamp = sysdate()
FROM
(
WITH has_dca_logs AS (
SELECT
tx_id,
decoded_log:args:userKey::string AS …
```
> check for dca program call for is_dca_swap

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.yml
- tests/test_silver__decoded_instructions_jupiter_limit_signers.sql
- Add limit order related cols
- Flag to indicate whether a swap was initiated by Jupiter limit order
- List the source wallet that requested the limit order if the above is true
- Add tests for new columns + checks for the specific addresses that Jupiter limit orders use
- Will use FR'ed dev table to update prod
```
UPDATE solana.silver.swaps_intermediate_jupiterv6_2 AS p
SET 
is_limit_swap = d.is_limit_swap,
limit_requester = d.limit_requester,
modified_timestamp = sysdate()
FROM solana_dev.silver.swaps_intermediate_jupiterv6_2 AS d
WHERE 
p.swaps_intermediate_jupiterv6_id = d.swaps_intermediate_jupiterv6_id
and p.block_timestamp::date >= '2023-10-01'
and p.is_limit_swap is null;
```
Incremental on Medium
`18:33:15  1 of 1 OK created sql incremental model …
> An 5223/jupiter limit orders

- models/gold/gov/gov__fact_rewards_fee.sql
- models/gold/gov/gov__fact_rewards_fee.yml
Add `pubkey` column which will replace `vote_pubkey`, since the existing name assumes the rewards are always sent to the vote account which is not always true.
- Remove`vote_pubkey` by 2024-12-03
> add pubkey col

- models/gold/defi/defi__fact_stake_pool_actions.yml
We should only verify amounts as non-null when the transaction is successful. This is already done in the upstream silver models but was missed in the gold version.
This will fix alerting for all these
```
select *
from solana.defi.fact_stake_pool_actions
where amount is null
and succeeded = FALSE;
```
> only check amount when the tx is successful

- .github/workflows/dbt_run_macro_get_block_production.yml
- macros/bronze_api/get_block_production.sql
- This is a short term fix to get block production data flowing again. Long term we probably want to move this to a streamline pipeline or into regular model code
-  Quicknode only allows retrieving 5000 blocks at once, so code was refactored to get data in blocks of 5000 based on the start/end blocks of the epoch
Call to get the data in DEV
`dbt run-operation get_block_production -t dev`
```
17:02:59  Running with dbt=1.8.5
17:03:00  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
17:03:00  Registered adapter: snowflake=1.8.3
17:03:01  Found 398 models, 2476 data tests, 57 seeds, 7 operations, 5 analyses, 85 sources, 1106 macros
```
Data in DEV
``` …
```
> refactor using quicknode and latest liverquery function

- models/silver/liquidity_pool/silver__liquidity_pool_actions_meteora_dlmm.sql
- models/silver/liquidity_pool/silver__liquidity_pool_actions_meteora_dlmm.yml
- Meteora `removeAllLiquidity` actions occasionally have no transfer of tokens so previous logic didn't include these in the table. This update adds these events which will have `0` amounts and defaults to the first 'mint' that appears in the decoded instruction
- 33 txs affected
```
with prod_issues as (
select *
from solana.silver.decoded_instructions_combined
where program_id = 'LBUZKhRxPF3XUpBCjp4YzTKgLccjZhTSDM9YuVaPwxo'
and event_type IN ('removeLiquidityByRange','removeLiquidity','removeAllLiquidity','addLiquidityByStrategyOneSide','addLiquidityOneSide','addLiquidity','addLiquidityByWeight','addLiquidityByStrategy')
and tx_id not in (
select tx_id from solana.silver.liquidity_pool_actions_meteora_dlmm
where block_timestamp::date between '2024-10-01' and '2024-11-06' 
)
and …
```
> add missing meteora events without transfers

- .github/workflows/dbt_test_hourly.yml
- models/streamline/core/streamline__transactions_and_votes_missing_7_days.sql
- models/streamline/streamline__all_unknown_block_txs_real_time.sql
Tables created from running tests get dropped when the test runs before they are recreated. This is causing some runs of the streamline block txs requests to fail when it happens to run at the same time the test is running because the view is trying to reference the test output table to figure out retries. The test takes 8-15mins to complete and runs hourly so this is causing failed requests 1-3x per hour.
- Fix is to create a model that selects from the test output table immediately after the test command is completed
- DBT full refresh models do not have an accompanying DROP statement. This will ensure that the resource is always available for the streamline request view
- Change the view to query the model instead of the test output table
`dbt run -s …
> Fix table not found error for streamline block txs

- models/streamline/core/complete/streamline__complete_blocks_2.sql
Fix issue where block level data retrieved from QN comes back as `NULL` but is still being added to the complete table. This change will no longer put these into the complete table and thus the streamline view will automatically retry getting these blocks.
`dbt run -s streamline__complete_blocks_2 -t dev`
```
15:56:50  1 of 1 OK created sql incremental model streamline.complete_blocks_2 ........... [SUCCESS 81574 in 7.38s]
```
Manually checking one of the issue blocks would no longer be added to the complete table
```
SELECT
block_id,
error,
_partition_by_created_date,
_inserted_timestamp,
FROM
SOLANA.bronze.streamline_blocks_2
WHERE
data IS NOT NULL
AND _inserted_timestamp >= '2024-11-12 17:16:56.000 +0000'
AND block_id = 300991654
QUALIFY
row_number() OVER (
PARTITION BY block_id
ORDER …
```
> if block level data is null, don't mark it as complete

- models/silver/silver__blocks.sql
Do not select block data from bronze when the data is `NULL`. A valid block should never have `NULL` data so it should either have data populated after the request is retried or it will result in an error indicating that the slot was skipped
Example w/ existing problem record, now returns nothing
```
select *
from solana.bronze.streamline_blocks_2
where block_id = 302193434
and _inserted_timestamp >= current_date - 1
and block_id IS NOT NULL
and error IS NULL
and data:error::STRING IS NULL
and data IS NOT NULL;
```
> don't put null data into silver table

- models/gold/nft/nft__dim_nft_metadata.sql
- models/silver/metadata/silver__nft_collection.sql
- models/silver/metadata/silver__nft_collection_view.sql
- models/sources.yml
- Deprecate the nft collections table as this is no longer supported in the v2.0 solscan API. You cannot find a token's collection_id based using a token address 🤯 
New/Updated models run in DEV
`dbt run -s models/silver/metadata/silver__nft_collection_view.sql -t dev`
```
00:46:36  1 of 1 OK created sql view model silver.nft_collection_view .................... [SUCCESS 1 in 2.47s]
```
`dbt build -s models/gold/nft/nft__dim_nft_metadata.sql`
```
00:48:42  1 of 13 OK created sql view model nft.dim_nft_metadata ......................... [SUCCESS 1 in 3.32s]
00:48:49  Finished running 1 view model, 12 data tests, 5 project hooks in 0 hours 0 minutes and 24.52 seconds (24.52s).
00:48:50  
00:48:50  
00:48:50  Done. PASS=13 WARN=0 ERROR=1 SKIP=0 TOTAL=14
```
> deprecate and source as view

- models/silver/backfill/silver__backfill_transactions_units_consumed.sql
- Update backfill model to only insert records
- insert takes a few seconds vs minutes for the merge https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01b88c3e-0612-4260-3d4f-8302a9350d07/detail
Same counts returned
```
select count(*) ct, 'dev' as source from solana_dev.silver.backfill_transactions_units_consumed
where _partition_id between 48924 and 48929
union 
select count(*) ct, 'prod' as source from solana.silver.backfill_transactions_units_consumed
where _partition_id between 48924 and 48929;
```
> remove unique_key to insert only

- .github/workflows/dbt_run_streamline_solscan_token_list.yml
- models/bronze/streamline/bronze__streamline_FR_solscan_token_list.sql
- models/bronze/streamline/bronze__streamline_solscan_token_list.sql
- models/sources.yml
- models/streamline/token/metadata/streamline__solscan_token_list_by_market_cap.sql
- Add streamline call for solscan v2 token list api
- Can no longer sort by volume so we will sort by market cap instead
- Doesnt have the same fields output...so we only have the basics like `name`, `symbol`, and `decimal`
- Add bronze models to query raw data
- Add workflow to call token list once per week 
`dbt run -s streamline__solscan_token_list_by_market_cap -t dev --vars '{STREAMLINE_INVOKE_STREAMS: True}'`
```
01:30:29  Running macro `if_data_call_function`: Calling udf streamline.udf_bulk_rest_api_v2 with params: 
{
"external_table": "solscan_token_list",
"producer_batch_size": "250",
"sql_limit": "250",
"worker_batch_size": "250"
}
01:30:37  1 of 1 OK created sql view model …
```
> Migrate solscan token metadata to solscan v2

- .github/workflows/dbt_run_decode_instructions.yml
- .github/workflows/dbt_run_decode_instructions_orchestrator.yml
- .github/workflows/dbt_run_decode_instructions_pyth.yml
- .github/workflows/dbt_run_decode_logs.yml
- .github/workflows/dbt_run_decode_logs_orchestrator.yml
- macros/create_udfs.sql
- macros/streamline/streamline_udfs.sql
- models/bronze/streamline/bronze__streamline_FR_decoded_instructions_3.sql
- models/bronze/streamline/bronze__streamline_FR_decoded_logs_2.sql
- models/bronze/streamline/bronze__streamline_decoded_instructions_3.sql
- models/bronze/streamline/bronze__streamline_decoded_logs_2.sql
- models/sources.yml
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_3.sql
- models/streamline/decode_instructions/streamline__complete_decoded_instructions_3_backfill.sql
- models/streamline/decode_instructions/streamline__decode_instructions_3_pyth_realtime.sql
- models/streamline/decode_instructions/streamline__decode_instructions_3_realtime.sql
- models/streamline/decode_logs/streamline__complete_decoded_logs_2.sql
- models/streamline/decode_logs/streamline__complete_decoded_logs_2_backfill.sql
- models/streamline/decode_logs/streamline__decode_logs_2_realtime.sql
- Add streamline 2.0 decoding API UDFs
- Add bronze models for decoded instructions and decoded logs pointing at streamline 2.0 raw data
- Add streamline models to make decoding requests to 2.0 pipeline
- Update workflows to call streamline 2.0 decoding requests in parallel with existing
decoded instructions in DEV
```
select *
from solana_dev.bronze.streamline_decoded_instructions_3
limit 1000;
```
decoded logs in DEV
```
select *
from solana_dev.bronze.streamline_decoded_logs_2
limit 1000;
```
> Migrate solana decoder to streamline 2

- models/silver/liquidity_pool/silver__burns_orca_non_whirlpool.yml
- models/silver/liquidity_pool/silver__mints_orca_non_whirlpool.yml
- models/silver/liquidity_pool/silver__pool_transfers_orca_non_whirlpool.yml
- Increase recency test range to 14 days for Orca non-whirlpool events
> recency range on non-whirlpool

- .github/workflows/dbt_run_backfill_transfers_mints.yml
- models/silver/backfill/silver__transfers_null_mints_fix.sql
Run this backfill backwards to ensure all the missing mints are `WSOL` so that we can run a simple update statement. Scheduled workflows have to be in main branch so we are forced to merge this into main even though this table will only live in dev
> temporary job to check if all null mints are wsol

- .github/workflows/dbt_run_streamline_solscan_blocks.yml
- models/bronze/streamline/bronze__streamline_FR_helius_blocks.sql
- models/bronze/streamline/bronze__streamline_helius_blocks.sql
- models/silver/non_core/silver___blocks_tx_count.sql
- models/sources.yml
- models/streamline/core/realtime/streamline__helius_blocks.sql
Temporarily get tx counts from helius (although we also have limited credits there and it won't support a full month) until we are back up w/ Solscan. Last resort we can switch the helius endpoint to quicknode but I would rather not verify data using the same source as `block_txs`.
I think this pipeline is important enough to warrant usage of the helius credits as we are really dependent on this to self-heal txs which we do often.
Incremental
`dbt run -s silver___blocks_tx_count -t dev`
```
17:06:38  1 of 1 OK created sql incremental model silver._blocks_tx_count ................ [SUCCESS 900 in 8.39s]
```
New tx counts in dev thats not in prod
```
select block_id
from solana_dev.silver._blocks_tx_count
where block_id >= 305000000
and transaction_count is not null
except 
select block_id …
```
> Add backup block txs count pipeline

- .github/workflows/dbt_run_decode_instructions.yml
- .github/workflows/dbt_run_decode_instructions_pyth.yml
- macros/helpers/decoded_instructions_backfill_helpers.sql
- models/silver/parser/silver__decoded_instructions.sql
- models/streamline/decode_instructions/streamline__decode_instructions_3_pyth_realtime.sql
- models/streamline/decode_instructions/streamline__decode_instructions_3_realtime.sql
> [!IMPORTANT]  
> This will not be merged until **Monday 12/9 630am PT**
- Remove calls to legacy pipeline
- Modify realtime queries to match existing but using `streamline.complete_decoded_instructions_3`
- Modify `silver.decoded_instructions` to use streamline 2.0 upstream data after cutoff data `2024-12-09`
- Temporarily extend lookback window
- Modify backfill macro to call streamline 2.0 endpoint
Streamline models run on DEV
`dbt run -s streamline__decode_instructions_3_realtime -t dev`
```
17:30:44  1 of 1 OK created sql table model streamline.decode_instructions_3_realtime .... [SUCCESS 1 in 528.25s]
```
`dbt run -s streamline__decode_instructions_3_pyth_realtime -t dev`
```
17:32:40  1 of 1 OK created sql view model streamline.decode_instructions_3_pyth_realtime  [SUCCESS 1 in …
```
> Deprecate legacy decode instructions pipeline

- .github/workflows/dbt_run_decode_logs.yml
- models/silver/parser/silver__decoded_logs.sql
- models/streamline/decode_logs/streamline__decode_logs_2_realtime.sql
> [!NOTE] 
> This will not be merged until afternoon of `2024-12-11` PT
See original [PR](https://github.com/FlipsideCrypto/solana-models/pull/726) that was reverted for context.
Additional changes here:
- Adjust legacy cutoff date to `2024-12-11`
- Change how `block_timestamp`, `succeeded` and `signers` are retrieved in `silver.decoded_logs`
Silver table updated w/ new dev data shows columns are now populated correctly
> Deprecate legacy decode logs pipeline - attempt #2

- models/silver/idls/silver__verified_user_idls.sql
- v2 version correctly validates IDL's such as `GovMaiHfpVPw8BAM1mbdzgmSZYDw2tdP32J2fapoQoYs`
> use verify_idl_v2 macro

- models/streamline/core/realtime/streamline__helius_blocks.sql
Switch the endpoint to get block tx counts from `helius` to `ankr`
`dbt run --vars '{STREAMLINE_INVOKE_STREAMS: True}' -s streamline__helius_blocks -t dev`
```
{
"external_table": "helius_blocks",
"producer_batch_size": "1000",
"sql_limit": "10000",
"worker_batch_size": "1000"
}
00:24:34  1 of 1 OK created sql view model streamline.helius_blocks ...................... [SUCCESS 1 in 11.42s]
```
Data in Dev
```
select *
from solana_dev.bronze.streamline_helius_blocks
where _partition_by_created_date = '2024_12_12'
limit 10;
```
> switch to ankr as provider for tx counts

- models/descriptions/tx_index.md
- models/silver/core/silver__transactions.sql
- models/silver/core/silver__transactions.yml
- Add `tx_index` column to `silver.transactions`
- Run DML before merging so that references to `{{ this }}` that selects all the columns in the model will work correctly
```
ALTER TABLE solana.silver.transactions
ADD COLUMN tx_index INTEGER;
```
- Add better filtering on data tests 
`dbt run -s silver__transactions -t dev`
```
00:32:32  1 of 13 OK created sql incremental model silver.transactions ................... [SUCCESS 1507135 in 245.06s]
```
Data in DEV
```
-- No new txs without tx_index
select count(*)
from solana_dev.silver.transactions
where _partition_id > 150217
and tx_index is null;
-- tx index is populated
select block_id, tx_id, tx_index
from solana_dev.silver.transactions
where _partition_id > 150217
and tx_index is not null
limit 10;
```
> add tx_index for data sourced from streamline 2.0

- macros/helpers/nft_compressed_mints_backfill_helpers.sql
- macros/streamline/streamline_udfs.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_mints.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_sales_magic_eden.sql
- models/bronze/bronze_api/bronze_api__parse_compressed_nft_sales_solsniper.sql
- Set `max_batch_rows` to be same as v1 call
- Update usages to use `v2`
Results for all 3 models in DEV
> Migrate compressed mint calls to streamline 2.0

- models/silver/core/silver__blocks.sql
Use default values for situations where the pre-model query is unable to retrieve one or both date values
I forced it to run the default values part of the code by hardcoding the last predicate in `get_dates_to_load_query` as there is no streamline data between these times
```
WHERE
_inserted_timestamp > '2024-12-19 12:16:44'
AND _inserted_timestamp < '2024-12-19 13:03:00'
```
I then ran compile to see that valid timestamp/date values were inserted into the query
`dbt compile -s silver__blocks -t prod`
```
/*
This CTE (pre_final) combines data from two sources:
1. Legacy data from 'bronze__blocks2' for blocks before the cutover_block_id
2. New data using streamline 2.0 raw data from 'bronze__streamline_blocks_2' for blocks after and including the cutover_block_id
*/
WITH pre_final AS ( …
```
> set sane defaults when unable to retrieve dates in pre-model query

- models/silver/liquidity_pool/orca/v1/silver__initialization_pools_orcav1.sql
- models/silver/liquidity_pool/orca/v1/silver__initialization_pools_orcav1.yml
- Create Orca V1 pool initializations model
- No new pools created since 2021 as this program is now deprecated, so we shouldn't expect new pools. Because of this I think we can run this just one time and leave it off the scheduler
- Slightly diff than V2 model as the mint data is not available in `post_token_balances`. Instead use LQ to get the account mints directly from Quicknode. There are only `27` pools and we only have to do this once.
`dbt build -s silver__initialization_pools_orcav1 -t dev --full-refresh`
```
15:33:57  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 33.89 seconds (33.89s).
15:33:58  
15:33:58  Completed successfully
15:33:58  
15:33:58  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
Incremental logic in place and …
> Orcav1 initialization pools

- models/descriptions/token_a_amount.md
- models/descriptions/token_b_amount.md
- models/silver/liquidity_pool/orca/silver__liquidity_pool_actions_orcav2.sql
- models/silver/liquidity_pool/orca/silver__liquidity_pool_actions_orcav2.yml
- Create `silver__liquidity_pool_actions_orcav2` to capture deposits and withdraws for v2 pools
- Uses decoded instructions and transfers as upstreams
> [!NOTE]
> We will need to backfill this table in batches before merging which will take a few hours total on 2xl
`dbt build -s silver__liquidity_pool_actions_orcav2 -t dev-2xl --full-refresh`
```
05:41:25  Finished running 1 incremental model, 19 data tests, 7 project hooks in 0 hours 31 minutes and 25.78 seconds (1885.78s).
05:41:25  
05:41:25  Completed successfully
05:41:25  
05:41:25  Done. PASS=20 WARN=0 ERROR=0 SKIP=0 TOTAL=20
```
Incremental on next 6 months of data
```
15:14:22  1 of 20 OK created sql incremental model silver.liquidity_pool_actions_orcav2 .. [SUCCESS 11399 in 1125.66s]
15:14:34  Finished running 1 incremental …
```
> Orca v2 lp actions

- models/silver/liquidity_pool/orca/v1/silver__liquidity_pool_actions_orcav1.sql
- models/silver/liquidity_pool/orca/v1/silver__liquidity_pool_actions_orcav1.yml
- Create `silver__liquidity_pool_actions_orcav1` to capture deposits and withdraws for v1 pools
- Uses decoded instructions and transfers as upstreams
- There are issues with data before `2021-03-17`. These records have been omitted from the model
> [!NOTE]
> We will need to backfill this table in batches before merging which will take a ~1 hour total on 2xl
`dbt build -s silver__liquidity_pool_actions_orcav1 -t dev-2xl --full-refresh`
```
17:47:59  1 of 20 OK created sql incremental model silver.liquidity_pool_actions_orcav1 .. [SUCCESS 1 in 457.93s]
17:48:08  Finished running 1 incremental model, 19 data tests, 7 project hooks in 0 hours 8 minutes and 1.40 seconds (481.40s).
17:48:08  
17:48:08  Completed successfully
17:48:08  
17:48:08  Done. PASS=20 WARN=0 ERROR=0 SKIP=0 TOTAL=20
``` …
> Orca v1 lp actions

- models/silver/liquidity_pool/raydium/cpmm/silver__liquidity_pool_actions_raydium_cpmm.sql
- models/silver/liquidity_pool/raydium/cpmm/silver__liquidity_pool_actions_raydium_cpmm.yml
- Create `silver__liquidity_pool_actions_raydium_cpmm` to capture deposits and withdraws for cpmm pools
- Uses decoded instructions and transfers as upstreams
- There are some null `token_a_*` values...These don't have any transfers attached to them. I decided to leave those in the model and adding a semi-arbitrary threshold count to send an error. Example `499C2J1gUdh3rHtQPZcUHXkC7dcV1e4vVLUN48TrGU36GrCXhdne7EzF1Qp1pYbYUbV7mMFvC7S13TWeMx6Tjx6S`
> [!NOTE]
> We will need to backfill this table in batches before merging which will take a ~3 hour total on 2xl
`dbt build -s silver__liquidity_pool_actions_raydium_cpmm -t dev-2xl --full-refresh`
```
04:19:35  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 36 minutes and 53.08 seconds (2213.08s).
04:19:35 …
```
> Raydium cpmm lp actions

- models/silver/liquidity_pool/raydium/clmm/silver__liquidity_pool_actions_raydium_clmm.sql
- models/silver/liquidity_pool/raydium/clmm/silver__liquidity_pool_actions_raydium_clmm.yml
- Create `silver__liquidity_pool_actions_raydium_clmm` to capture deposits and withdraws for clmm pools
- Uses decoded instructions and transfers as upstreams
- There are issues with 11 decreaseLiquidity events on `2022-11-06`. These records have been omitted from the model
- There are still some null `token_a_*` values...There just simply arent any transfers attached to them. I decided to leave those in the model and adding a semi-arbitrary threshold count to send an error. Example `5ZnZ5PfKtMxG9ZTCTwc2de5X5eQCmwUQtbaqGiqawxPgEYkDeGsLgScoMSLb9YKQtsww9g3WhphmPjCwNsK9jsxs`
> [!NOTE]
> We will need to backfill this table in batches before merging which will take a ~3 hour total on 2xl
`dbt run -s silver__liquidity_pool_actions_raydium_clmm -t dev-2xl --full-refresh`
```
16:38:08  Finished …
```
> Create Raydium CLMM LP Actions

- models/silver/liquidity_pool/raydium/v4/silver__initialization_pools_raydiumv4.sql
- models/silver/liquidity_pool/raydium/v4/silver__initialization_pools_raydiumv4.yml
- Create `silver__initialization_pools_raydiumv4` to capture lp pools being created
- `~157` decoded records seem to have "bad" data (issue w/ the actual instruction) but hasnt happened since late 2022. I have removed these from the model
`dbt build -s silver__initialization_pools_raydiumv4 -t dev --full-refresh`
```
15:23:21  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 1 minutes and 46.54 seconds (106.54s).
15:23:21  
15:23:21  Completed successfully
15:23:21  
15:23:21  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
`dbt build -s silver__initialization_pools_raydiumv4 -t dev`
```
15:24:36  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 46.32 seconds (46.32s).
15:24:36  
15:24:36  Completed successfully …
```
> Raydium v4 initialize pools

- models/silver/liquidity_pool/raydium/cpmm/silver__initialization_pools_raydium_cpmm.sql
- models/silver/liquidity_pool/raydium/cpmm/silver__intialization_pools_raydium_cpmm.yml
- Create `silver__initialization_pools_raydium_cpmm` to capture lp pools being created
`dbt build -s silver__initialization_pools_raydium_cpmm -t dev --full-refresh`
```
16:54:48  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 40.14 seconds (40.14s).
16:54:48  
16:54:48  Completed successfully
16:54:48  
16:54:48  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
`dbt build -s silver__initialization_pools_raydium_cpmm -t dev`
```
16:55:31  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 34.61 seconds (34.61s).
16:55:31  
16:55:31  Completed successfully
16:55:31  
16:55:31  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
Data in dev
```
select *
from …
```
> Raydium CPMM Initialize Pools

- models/silver/liquidity_pool/raydium/clmm/silver__initialization_pools_raydium_clmm.sql
- models/silver/liquidity_pool/raydium/clmm/silver__initialization_pools_raydium_clmm.yml
- Create `silver__initialization_pools_raydium_clmm` to capture lp pools being created
- CLMM pools do not have LP mints. I decided to still include the column to keep the schema standardized between all silver layer initialization pool models. It will always be NULL for this model
`dbt build -s silver__initialization_pools_raydium_clmm -t dev --full-refresh`
```
17:07:30  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 45.50 seconds (45.50s).
17:07:30  
17:07:30  Completed successfully
17:07:30  
17:07:30  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
`dbt build -s silver__initialization_pools_raydium_clmm -t dev`
```
17:10:07  Finished running 1 incremental model, 16 data tests, 7 project hooks in 0 hours 0 minutes and 29.63 seconds …
```
> Raydium CLMM Initialize Pools

- models/silver/liquidity_pool/raydium/stable/silver__initialization_pools_raydiumstable.sql
- models/silver/liquidity_pool/raydium/stable/silver__initialization_pools_raydiumstable.yml
- Create `silver__initialization_pools_raydiumstable` to capture lp pools being created
- Only 3 total pools
- Will only be run once so no scheduler
`dbt build -s silver__initialization_pools_raydiumstable -t dev --full-refresh`
```
16:21:20  Finished running 1 incremental model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 31.23 seconds (31.23s).
16:21:21  
16:21:21  Completed successfully
16:21:21  
16:21:21  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
Data in dev
```
select *
from solana_dev.silver.initialization_pools_raydiumstable
limit 100;
```
> Raydium Stable Initialize Pools

- models/silver/liquidity_pool/meteora/amm/silver__initialization_pools_meteora.sql
- models/silver/liquidity_pool/meteora/amm/silver__initialization_pools_meteora.yml
- Create `silver__initialization_pools_meteora` to capture lp pools being created
- event type `initializePermissionedPool` does not provide pool token A/B account values in the instruction. It says it does, but they are actually the token A/B authorities, not the vaults. There are 27 of these and they should produce warnings in the tests or errors if we receive more than 27 records with a NULL token A/B account
`dbt build -s silver__initialization_pools_meteora -t dev-2xl --full-refresh`
```
16:35:44  Finished running 1 incremental model, 16 data tests, 7 project hooks in 0 hours 0 minutes and 29.29 seconds (29.29s).
16:35:44  
16:35:44  Completed with 2 warnings:
16:35:44  
16:35:44  Warning in test not_null_silver__initialization_pools_meteora_TOKEN_A_ACCOUNT …
```
> Meteora AMM initialize pools

- models/silver/liquidity_pool/orca/whirlpool/silver__initialization_pools_orca_whirlpool.sql
- models/silver/liquidity_pool/orca/whirlpool/silver__initialization_pools_orca_whirlpool.yml
- models/silver/liquidity_pool/orca/whirlpool/silver__liquidity_pool_actions_orca_whirlpool.sql
- models/silver/liquidity_pool/orca/whirlpool/silver__liquidity_pool_actions_orca_whirlpool.yml
- Create `silver__initialization_pools_orca_whirlpool` to capture lp pools being created
`dbt build -s silver__initialization_pools_orca_whirlpool -t dev-2xl --full-refresh`
```
17:45:06  Finished running 1 incremental model, 16 data tests, 7 project hooks in 0 hours 0 minutes and 40.79 seconds (40.79s).
17:45:06  
17:45:06  Completed successfully
17:45:06  
17:45:06  Done. PASS=17 WARN=0 ERROR=0 SKIP=0 TOTAL=17
```
`dbt build -s silver__initialization_pools_orca_whirlpool -t dev-2xl`
```
17:45:58  Finished running 1 incremental model, 16 data tests, 7 project hooks in 0 hours 0 minutes and 36.61 seconds (36.61s).
17:45:59  
17:45:59  Completed successfully
17:45:59  
17:45:59  Done. PASS=17 WARN=0 ERROR=0 SKIP=0 TOTAL=17
```
Data in dev
```
select *
from …
```
> Orca Whirlpool Initialize Pools

- models/silver/swaps/bonkswap/silver__swaps_intermediate_bonkswap.sql
- models/silver/swaps/bonkswap/silver__swaps_intermediate_bonkswap.yml
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora.sql
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora.yml
- models/silver/swaps/phoenix/silver__swaps_intermediate_phoenix.sql
- models/silver/swaps/phoenix/silver__swaps_intermediate_phoenix.yml
surface `index`/`inner_index` in silver swaps models needed for marinade curation
- will update `index`/`inner_index` in prod after merge by FR'ing `dev` and using ad-hoc `update` statement
dbt runs successful:
```
18:07:53  1 of 3 OK created sql incremental model silver.swaps_intermediate_bonkswap ..... [SUCCESS 229 in 28.91s]
18:07:53  3 of 3 OK created sql incremental model silver.swaps_intermediate_phoenix ...... [SUCCESS 8702 in 29.36s]
18:08:02  2 of 3 OK created sql incremental model silver.swaps_intermediate_meteora ...... [SUCCESS 75423 in 37.93s]
```
> suface index/inner_index

- models/gold/marinade/marinade__dim_pools.sql
- models/gold/marinade/marinade__dim_pools.yml
- Create `marinade__dim_pools`
- Pool dimension for any pool that has `msol` or `mnde` as one of the liquidity pairs
- Add symbol + other meta
`dbt build -s marinade__dim_pools -t dev --full-refresh`
```
18:01:52  Finished running 1 incremental model, 18 data tests, 7 project hooks in 0 hours 0 minutes and 36.35 seconds (36.35s).
18:01:52  
18:01:52  Completed successfully
18:01:52  
18:01:52  Done. PASS=19 WARN=0 ERROR=0 SKIP=0 TOTAL=19
```
`dbt build -s marinade__dim_pools -t dev`
```
18:02:35  Finished running 1 incremental model, 18 data tests, 7 project hooks in 0 hours 0 minutes and 31.75 seconds (31.75s).
18:02:35  
18:02:35  Completed successfully
18:02:35  
18:02:35  Done. PASS=19 WARN=0 ERROR=0 SKIP=0 TOTAL=19
```
Data in dev
```
select *
from solana_dev.marinade.dim_pools;
```
> Marinade dim pools

- models/gold/marinade/marinade__dim_pools.sql
- models/gold/marinade/marinade__ez_liquidity_pool_actions.sql
- models/gold/marinade/marinade__ez_liquidity_pool_actions.yml
- models/gold/marinade/marinade__meteora_dlmm_pivot.sql
- models/gold/marinade/marinade__meteora_dlmm_pivot.yml
- models/gold/marinade/marinade__meteora_pivot.sql
- models/gold/marinade/marinade__meteora_pivot.yml
- Create `marinade__ez_liquidity_pool_actions` to surface `deposit` and `withdraw` events for all pools that use either MSOL or MNDE as one of the LP pairs
- upstream Meteora LP data has a different schema than the rest so I am temporarily creating 2 views to reshape the data for the purposes of marinade
- `marinade__meteora_pivot` and `marinade__meteora_dlmm_pivot`
- These should only be materialized once, but tests should/will run daily
`dbt build -s marinade__meteora_dlmm_pivot -t dev`
```
20:00:32  Finished running 1 view model, 5 data tests, 7 project hooks in 0 hours 0 minutes and 41.20 seconds (41.20s).
20:00:32  
20:00:32  Completed successfully
20:00:32  
20:00:32  Done. PASS=6 WARN=0 ERROR=0 SKIP=0 TOTAL=6
```
`dbt build -s marinade__meteora_pivot -t dev`
```
20:04:56  Finished …
```
> Marinade ez pool lp actions

- models/gold/marinade/marinade__ez_liquid_staking_actions.sql
- models/gold/marinade/marinade__ez_liquid_staking_actions.yml
- models/silver/parser/silver__decoded_instructions_combined.yml
- models/silver/protocols/marinade/silver__marinade_liquid_staking_actions.sql
- models/silver/protocols/marinade/silver__marinade_liquid_staking_actions.yml
Create silver and gold `liquid_staking_actions` table for marinade
fr on 2xl:
gold: `00:17:22  1 of 1 OK created sql incremental model marinade.ez_liquid_staking_actions ..... [SUCCESS 1 in 10.87s]`
silver: `00:09:58  1 of 2 OK created sql incremental model silver.marinade_liquid_staking_actions . [SUCCESS 1 in 611.05s]`
incremental:
gold: `00:59:13  1 of 1 OK created sql incremental model marinade.ez_liquid_staking_actions ..... [SUCCESS 4 in 9.96s]`
silver: `00:46:44  1 of 2 OK created sql incremental model silver.marinade_liquid_staking_actions . [SUCCESS 4 in 14.32s]`
test:
```
00:45:03  Finished running 50 data tests, 7 project hooks in 0 hours 1 minutes and 15.51 seconds (75.51s).
00:45:04  
00:45:04  Completed successfully
00:45:04  
00:45:04  Done. PASS=50 WARN=0 ERROR=0 SKIP=0 …
```
> marinade ez liquid staking

- macros/helpers/decoded_instructions_backfill_helpers.sql
- macros/helpers/decoded_logs_backfill_helpers.sql
Add macro helpers for backfilling decoder instructions and logs for a specific `block_timestamp::date`. This can be useful for situations where there are significant raw data ingestion delays as the current real-time streamline requests only have a 2 day lookback.
`dbt run-operation decoded_logs_backfill_retry_single_date_all_programs --args '{"backfill_date": "2024-12-15"}' -t dev`
`dbt run-operation decoded_instructions_backfill_single_date_all_programs --args '{"backfill_date": "2024-12-15"}' -t dev`
> Add decoder backfill helper for single dates

- .github/workflows/dbt_run_streamline_solscan_blocks.yml
- models/silver/non_core/silver___blocks_tx_count.sql
Revert back to using `solscan` raw data for block tx counts (reverts this [change](https://github.com/FlipsideCrypto/solana-models/pull/729/files#diff-33db680672616b55cc809252838d9bbd10a7eeb382a5b177d36d3a1b169200f7)).
> Switch block tx counts back to solscan

- models/gold/marinade/marinade__ez_liquidity_pool_actions.sql
- models/gold/marinade/marinade__meteora_dlmm_pivot.sql
- models/gold/marinade/marinade__meteora_multi_pivot.sql
- models/gold/marinade/marinade__meteora_multi_pivot.yml
- models/gold/marinade/marinade__meteora_pivot.sql
Add pool from meteora multi to the marinade lp actions output
- Add pivoted view for meteora multi lp actions
- Add to `marinade.ez_liquidity_pool_actions`
- Cleanup TODOs from other meteora pivot tables
`dbt build -s marinade__meteora_multi_pivot -t dev`
```
15:32:05  Finished running 1 view model, 5 data tests, 7 project hooks in 0 hours 0 minutes and 23.77 seconds (23.77s).
15:32:06  
15:32:06  Completed successfully
15:32:06  
15:32:06  Done. PASS=6 WARN=0 ERROR=0 SKIP=0 TOTAL=6
```
`dbt build -s marinade__ez_liquidity_pool_actions -t dev --full-refresh`
```
15:33:57  Finished running 1 incremental model, 18 data tests, 7 project hooks in 0 hours 1 minutes and 8.61 seconds (68.61s).
15:33:57  
15:33:57  Completed successfully
15:33:57  
15:33:57  Done. PASS=19 WARN=0 ERROR=0 SKIP=0 …
```
> Add meteora multi swap for marinade

- models/gold/core/core__fact_transactions.sql
- models/gold/core/core__fact_transactions.yml
- Add `tx_index` column to `core.fact_transactions`
`dbt build -s core__fact_transactions -t dev`
```
17:03:51  Finished running 1 view model, 17 data tests, 7 project hooks in 0 hours 0 minutes and 32.64 seconds (32.64s).
17:03:52  
17:03:52  Completed successfully
17:03:52  
17:03:52  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
Data in Dev
```
select *
from solana_dev.core.fact_transactions
where tx_index is not null
limit 10;
```
> add tx_index to gold

- models/bronze/streamline/bronze__streamline_FR_block_tx_index_backfill.sql
- models/bronze/streamline/bronze__streamline_block_tx_index_backfill.sql
- models/silver/backfill/silver__backfill_transactions_index.sql
- models/streamline/core/realtime/streamline__block_txs_index.sql
Change partition key to every 15 minutes to lower run time required to update the silver table. Anything under 5 mins should be OK.
- I will have to move the existing data into a new partition and reload the existing silver table before turning the job back on.
I ran 4 iterations in DEV and times were fairly consistent and all under 5 mins
```
15:57:14  1 of 1 OK created sql incremental model silver.backfill_transactions_index ..... [SUCCESS 70321795 in 138.87s]
16:10:15  1 of 1 OK created sql incremental model silver.backfill_transactions_index ..... [SUCCESS 70507472 in 130.02s]
16:23:40  1 of 1 OK created sql incremental model silver.backfill_transactions_index ..... [SUCCESS 68996177 in 184.72s]
16:33:55  1 of 1 OK created sql incremental model silver.backfill_transactions_index ..... …
```
> change partition key to 15min intervals instead of daily

- models/gold/gov/gov__fact_block_production.sql
- models/silver/validator/silver__historical_block_production.sql
- models/silver/validator/silver__snapshot_block_production.sql
- models/silver/validator/silver__snapshot_block_production_2.sql
- models/silver/validator/silver__snapshot_block_production_2.yml
- models/silver/validator/silver__snapshot_block_production_view.sql
- models/sources.yml
Fix for [issue](https://team-1612274056224.atlassian.net/browse/AN-5658) surfaced by marqu
- Get epoch start/end slots from `silver.epoch` as the start/end slot from the raw data is the start/end of the blocks requested in each individual RPC call and no longer the start/end of the entire epoch
- Deprecate existing `snapshot_block_production` model and put it as part of historical view
- I tried just refreshing the data but for unknown reasons some data in epoch `552` and before was missing
- Add new model `snapshot_block_production_2` to capture all block production data after epoch `552`
- Aggregate leader and block produced values by epoch in gold for all data from `snapshot_block_production_2`
`dbt run -s silver__snapshot_block_production_view silver__historical_block_production -t …
> fix bad epoch start/end slots

- macros/helpers/decoded_instructions_backfill_helpers.sql
- macros/helpers/decoded_logs_backfill_helpers.sql
Filter down events for single day retries to only get data that isnt already in silver or has an error/incomplete decoding in silver
```
(dbt-env) ➜  solana-models git:(only-retry-null-or-error-for-single-date-retries) ✗ dbt run-operation decoded_instructions_backfill_retry_single_date_all_programs --args '{"backfill_date": "2023-09-09"}' -t dev
dbt run-operation decoded_logs_backfill_retry_single_date_all_programs --args '{"backfill_date": "2023-09-09"}' -t dev
16:37:57  Running with dbt=1.8.5
16:37:58  [WARNING]: Deprecated functionality
The `tests` config has been renamed to `data_tests`. Please see
https://docs.getdbt.com/docs/build/data-tests#new-data_tests-syntax for more
information.
16:37:58  Registered adapter: snowflake=1.8.3
16:37:59  Found 464 models, 2934 data tests, 58 …
```
> only resend if not exist or error in silver for single day retries

- models/gold/defi/defi__fact_bridge_activity.sql
- models/silver/bridges/silver__bridge_mayan_transfers.sql
- models/silver/bridges/silver__bridge_mayan_transfers_decoded.sql
- models/silver/bridges/silver__bridge_mayan_transfers_decoded.yml
- models/silver/bridges/silver__bridge_mayan_transfers_view.sql
- models/sources.yml
Create new silver mayan bridge table using decoded data. No events using the old program_id have landed in the table since `2024-12-23`, and the decoded table allows us to get the bridge events using the newer structure.
- convert old table into view
- Legacy and new table do not overlap so directly added it into the gold view
Runs:
- FR on 2xl
`00:12:26  1 of 1 OK created sql incremental model silver.bridge_mayan_transfers_decoded .. [SUCCESS 1 in 195.91s]
`
- incremental on med
`00:31:50  1 of 1 OK created sql incremental model silver.bridge_mayan_transfers_decoded .. [SUCCESS 1426 in 31.48s]
`
- test:
```
00:15:32  Finished running 16 data tests, 7 project hooks in 0 hours 0 minutes and 49.62 seconds (49.62s).
00:15:32  
00:15:32  Completed successfully
00:15:32  
00:15:32  Done. …
```
> update mayan bridge

- models/bronze/stage/bronze__stage_block_txs_2.sql
- Exclude the `value` column from the output for `bronze.stage_block_txs_2`
- Extract only the data we need downstream from the value column 
- Reduces the amount written by about half which also then decreases run time
Existing
New
Existing
```
17:28:23  1 of 1 OK created sql incremental model bronze.stage_block_txs_2 ............... [SUCCESS 2100383 in 155.33s]
```
New
```
17:27:53  1 of 1 OK created sql incremental model bronze.stage_block_txs_2 ............... [SUCCESS 2100383 in 131.10s]
```
> stage block txs extract columns from value, don't include it in output

- models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql
- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
New JUPv6 IDL returns event_types and account name as snake case so update logic to filter for those
- table is stall since idl was updated yesterday so 1st run will take a while and will use 2xl for it
inc runs on 2xl
- 20:51:02  1 of 1 OK created sql incremental model silver.swaps_intermediate_jupiterv6_2 .. [SUCCESS 26590691 in 95.52s]
- 20:44:07  1 of 1 OK created sql incremental model silver.swaps_inner_intermediate_jupiterv6  [SUCCESS 13277181 in 113.31s]
> add snake case for jupv6

- models/silver/nfts/silver__nft_sales_tensor_bid.sql
- models/silver/parser/silver__decoded_instructions_combined.yml
Add takeBidLegacy NFT sales
- The `TCMPhJdwDryooaGtiocG1u3xcYbRpiJzb283XfCZsDp` program  is called `Tensor cNFT` but these sales are all standard NFTs, so added it to the `bid` model.
- Will have to FR model in between incremental runs
runs:
- fr on 2xl
`17:35:07  Finished running 1 incremental model, 7 project hooks in 0 hours 0 minutes and 53.67 seconds (53.67s).
`
- incremental on med
`17:36:41  1 of 1 OK created sql incremental model silver.nft_sales_tensor_bid ............ [SUCCESS 3 in 37.70s]`
- test
```
17:46:25  Finished running 18 data tests, 7 project hooks in 0 hours 0 minutes and 43.73 seconds (43.73s).
17:46:25  
17:46:25  Completed successfully
17:46:25  
17:46:25  Done. PASS=18 WARN=0 ERROR=0 SKIP=0 TOTAL=18
```
> add takeBidLegacy sales

- models/silver/nfts/silver__nft_sales_magic_eden_cnft.sql
- models/silver/nfts/silver__nft_sales_solsniper_cnft.sql
Add a buffer into the incremental combining our onchain cNFT data and decoded mints -- cNFT decoding for mints sometimes lands later into bronze, and the incremental doesn't pick it up in silver.
> add buffer to cnft sales

- models/silver/swaps/jupiter/v4/silver__swaps_inner_intermediate_jupiterv4.sql
- models/silver/swaps/jupiter/v4/silver__swaps_intermediate_jupiterv4_2.sql
- models/silver/swaps/jupiter/v6/silver__swaps_inner_intermediate_jupiterv6.sql
- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.sql
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora.sql
- models/silver/swaps/raydium/silver__swaps_intermediate_raydium_v4_amm.sql
For models where we need to reselect all tx_id's in the the incremental subset, include the block_timestamp in the initial select and use that as a filter to scan less of the decoded table
- this step seems to take the most time and which is in a number of models
The temp table creation runs considerable faster with the additional logic - example runs below:
- new logic: https://app.snowflake.com/us-east-1/vna27887/#/compute/history/queries/01ba2c71-0412-db47-3d4f-8302e81379cf/detail
- existing: https://app.snowflake.com/zsniary/exa10207/#/compute/history/queries/01ba2c60-0412-ddf6-3d4f-8302e811879b/detail
- incremental runs on medium
00:09:36  1 of 6 OK created sql incremental model silver.swaps_inner_intermediate_jupiterv4  [SUCCESS 89 in 42.49s]
00:09:46  4 of 6 OK created sql …
> use timestamp filter

- models/silver/liquidity_pool/meteora/amm/silver__liquidity_pool_actions_meteora_2.sql
- models/silver/liquidity_pool/meteora/amm/silver__liquidity_pool_actions_meteora_2.yml
Refactor LP actions model for `meteora amm` to latest standard schema
- A small amount of records for `removeLiquiditySingleSide` have no token transfers but only a burn action. There is no good way to consitently remove these from the output without removing legit records other than by using a inner join to `transfers`. I am hesitant to do that because that could introduce issues if there are missing records in transfers. I think I am ok w/ leaving this in the model since we can filter these out in `gold`.
- Added batch backfill logic that doesn't require editing the model before running
FR on 2xl
`dbt run -s silver__liquidity_pool_actions_meteora_2 -t dev-2xl --full-refresh`
```
01:05:12  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_meteora_2  [SUCCESS 1 in …
```
> Refactor lp actions meteora amm

- models/silver/liquidity_pool/meteora/dlmm/silver__liquidity_pool_actions_meteora_dlmm_2.sql
- models/silver/liquidity_pool/meteora/dlmm/silver__liquidity_pool_actions_meteora_dlmm_2.yml
- models/silver/parser/silver__decoded_instructions_combined.yml
Refactor LP actions model for meteora dlmm to latest standard schema
- A small amount of records for `removeAllLiquidity` have no token transfers. There is no good way to consistently remove these from the output without removing legit records other than by using a inner join to transfers. I am hesitant to do that because that could introduce issues if there are missing records in transfers. I think I am ok w/ leaving this in the model since we can filter these out in gold.
FR on 2xl on largest set of data which was inserted `Jan 2025` because of backfills
`dbt run -s silver__liquidity_pool_actions_meteora_dlmm_2 -t dev-2xl --full-refresh`
```
16:16:47  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_meteora_dlmm_2  [SUCCESS 1 in 924.97s]
```
Incremental on 2xl - 30 …
> Refactor lp actions meteora dlmm

- models/streamline/decode_instructions/streamline__decode_instructions_3_realtime.sql
- Refactor `decode_instructions_realtime_3`
- Use `silver.events_inner`
- Reference IDLs to decode as a static list
Existing
New (executed using prod upstreams)
Data in DEV
```
select count(*) from solana_dev.streamline.decode_instructions_3_realtime_test;
```
> Refactor decoded instructions realtime 3

- models/silver/bridges/silver__bridge_mayan_transfers_decoded.sql
- models/silver/liquidity_pool/orca/v1/silver__liquidity_pool_actions_orcav1.sql
- models/silver/liquidity_pool/orca/v2/silver__liquidity_pool_actions_orcav2.sql
- models/silver/liquidity_pool/orca/whirlpool/silver__liquidity_pool_actions_orca_whirlpool.sql
- models/silver/liquidity_pool/raydium/clmm/silver__liquidity_pool_actions_raydium_clmm.sql
- models/silver/liquidity_pool/raydium/cpmm/silver__liquidity_pool_actions_raydium_cpmm.sql
- models/silver/liquidity_pool/raydium/v4/silver__liquidity_pool_actions_raydiumv4.sql
- models/silver/nfts/silver__nft_mint_price_candy_machine.sql
- models/silver/nfts/silver__nft_sales_hadeswap_decoded.sql
- models/silver/nfts/silver__nft_sales_magic_eden_v2_decoded.sql
- models/silver/nfts/silver__nft_sales_solsniper.sql
- models/silver/nfts/silver__nft_sales_tensorswap.sql
- models/silver/protocols/marinade/silver__marinade_liquid_staking_actions.sql
- models/silver/swaps/phoenix/silver__swaps_intermediate_phoenix.sql
Optimize joins by filtering records in tables such as `transfers` with inner joins to base tables
- this initial PR makes updates to the tables that use `decoded_instructions_combined` and `{{ between_stmts }}` logic. Other models will be updated in future PRs.
Results in significant run time improvements, ie:
old:
-  `20:05:34  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_raydium_clmm  [SUCCESS 1921 in 105.12s]`
- `20:30:55  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_orca_whirlpool  [SUCCESS 38740 in 253.82s]`
new:
- `20:01:40  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_raydium_clmm  [SUCCESS 1921 in 26.61s]`
- `20:33:14  1 of 1 OK created sql incremental model silver.liquidity_pool_actions_orca_whirlpool …
> optimize cte distinct joins

- models/streamline/core/realtime/streamline__block_txs_index.sql
- Temporarily set different upstream to get blocks that errored from Ankr calls
- Switch to QN
- After this is done backfilling (~1 day) we should can switch to @tarikceric [PR](https://github.com/FlipsideCrypto/solana-models/pull/801) and continue from there
`dbt run -s streamline__block_txs_index --vars '{STREAMLINE_INVOKE_STREAMS: true, UPDATE_UDFS_AND_SPS: true}'`
```
16:16:55  1 of 1 OK created sql view model streamline.block_txs_index .................... [SUCCESS 1 in 87.96s]
```
> Backfill tx index re-request error responses

- models/silver/swaps/jupiter/v6/silver__swaps_intermediate_jupiterv6_2.yml
Pretty sure this is returning false positives 
```
select * from SOLANA.dbt_utils_expression_is_true_silver.swaps_intermediate_jupiterv6_2_IS_LIMIT_SWAP;
```
Because the account does swaps outside of the limit program and we only populater `IS_LIMIT_SWAP` if it is a certain signer _and_ there is a limit swap event in the same transaction. The test is only checking for the former condition.
`dbt test -s silver__swaps_intermediate_jupiterv6_2 -t prod`
```
17:07:32  Finished running 26 data tests, 7 project hooks in 0 hours 1 minutes and 13.67 seconds (73.67s).
17:07:33  
17:07:33  Completed successfully
17:07:33  
17:07:33  Done. PASS=26 WARN=0 ERROR=0 SKIP=0 TOTAL=26
```
> add requester predicate for Jup v6 test

- models/silver/validator/silver__snapshot_vote_accounts.sql
- Handle unix timestamp milliseconds using snowflake's [to_timestamp](https://docs.snowflake.com/en/sql-reference/functions/to_timestamp)
> handle millisecond unix timestamps using snowflake funcs

- models/silver/gauges/silver__gauges_votes_saber.sql
Pretty certain no one is looking at this...both `gauges` and `saber` are more or less defunct products. There are still events but few and far between. We can easily spin this back up and have it up to date if there is a true downstream use-case
> remove saber gauges from model updates

- models/gold/gov/gov__ez_staking_lp_actions.sql
- models/gold/gov/gov__ez_staking_lp_actions.yml
- models/gold/gov/gov__fact_staking_lp_actions.sql
- models/gold/gov/gov__fact_staking_lp_actions.yml
- models/silver/non_core/silver__staking_lp_actions.sql
- models/silver/non_core/silver__staking_lp_actions_labeled.sql
- Use `silver__staking_lp_actions_2` and `silver__staking_lp_actions_labeled_2` in gold
- Add `inner_index` to gold models
- `index` in gold is now an INT instead of STRING
- Deprecate v1 of the above models
`dbt build -s gov__fact_staking_lp_actions gov__ez_staking_lp_actions -t dev`
```
15:58:09  Finished running 2 view models, 32 data tests, 7 project hooks in 0 hours 0 minutes and 32.52 seconds (32.52s).
15:58:09  
15:58:09  Completed successfully
15:58:09  
15:58:09  Done. PASS=34 WARN=0 ERROR=0 SKIP=0 TOTAL=34
```
> replace v1 staking lp actions with v2, add inner_index to gold

- models/silver/gauges/silver__gauges_votes_saber.yml
- models/silver/liquidity_pool/raydium/cpmm/silver__liquidity_pool_actions_raydium_cpmm.sql
- Remove saber tests as the model is deprecated
- Add min amount condition for raydium LP cpmm as there was a new transaction that had no transfers. This should not be included in the output anymore
> Minor test fixes

- models/descriptions/__overview__.md
- models/gold/nft/nft__ez_nft_sales.sql
- models/gold/nft/nft__ez_nft_sales.yml
- models/silver/nfts/silver__nft_sales_legacy_combined_view.sql
[Diagram](https://www.figma.com/board/FEgtAnUWAqC8CSztLy97OA/Solana-EZ-NFT-Sales?node-id=0-1&p=f&t=u1Udnr2eIlbwqxcY-0)
Create `ez_nft_sales` table
- Follow EVM standard column naming where applicable
- clean up logic from old `fact` table via new intermediate silver table for deprecated models + setting variables for existing models
FR on 2xl
```
20:51:16  1 of 2 OK created sql view model silver.nft_sales_legacy_combined_view ......... [SUCCESS 1 in 4.15s]
20:52:20  2 of 2 OK created sql incremental model nft.ez_nft_sales ....................... [SUCCESS 1 in 63.67s]
```
Inc on med
`1 of 1 OK created sql incremental model nft.ez_nft_sales ....................... [SUCCESS 4 in 12.06s]
`
Test:
```
21:50:55  Finished running 52 data tests, 7 project hooks in 0 hours 1 minutes and 2.54 …
```
> An 5755/gold ez nft sales

- models/silver/governance/silver__gov_actions_marinade.sql
- models/silver/governance/silver__gov_actions_marinade_tmp.sql
Limit incremental to scan for last 3days of data (model is currently scanning large amounts of data due to large gap from most recent _inserted_timestamp)
ran successfully:
```
17:59:42  1 of 2 OK created sql incremental model silver.gov_actions_marinade_tmp ........ [SUCCESS 0 in 4.45s]
17:59:47  2 of 2 OK created sql incremental model silver.gov_actions_marinade ............ [SUCCESS 0 in 4.65s] 
```
> incremental filter to last 3 days

- dbt_project.yml
- macros/create_udfs.sql
- models/silver/core/silver__decoded_instructions_data.sql
- models/silver/core/silver__transfers.sql
- models/silver/non_core/silver__mint_actions.sql
1. Deprecate legacy `decoded_instructions_data` models
2. Use `events_inner` in `silver.transfers` and `silver.mint_actions`, in place of flattening `silver.events`
incremental on medium:
```
--01:36:17  1 of 1 OK created sql incremental model silver.mint_actions .................... [SUCCESS 76111 in 11.13s]
-- 00:51:25  1 of 1 OK created sql incremental model silver.transfers ....................... [SUCCESS 3871273 in 74.29s]
```
> An 5767/deprecate old decoder and optimizations

- models/gold/gov/gov__ez_staking_lp_actions.sql
- models/gold/gov/gov__ez_staking_lp_actions.yml
- models/silver/non_core/silver__staking_lp_actions_labeled_2.sql
- models/silver/non_core/silver__staking_lp_actions_labeled_2.yml
Add logic for new staking events `moveLamports` and `moveStake`
- add columns for move_destination and move_amount
Dev runs:
- Successful incremental run on the last month of data (since new event appeared):
`22:54:33  1 of 1 OK created sql incremental model silver.staking_lp_actions_labeled_2 .... [SUCCESS 8244606 in 237.43s]`
- Successful Incremental on gold:
`22:56:26  1 of 1 OK created sql view model gov.ez_staking_lp_actions ..................... [SUCCESS 1 in 2.97s]
`
- Testings passing on silver: 
```
22:59:37  Finished running 15 data tests, 6 project hooks in 0 hours 0 minutes and 40.03 seconds (40.03s).
22:59:38  
22:59:38  Completed successfully
22:59:38  
22:59:38  Done. PASS=15 WARN=0 ERROR=0 SKIP=0 TOTAL=15
```
> add move events

- models/silver/swaps/orca/token_swap/silver__swaps_intermediate_orca_token_swap.sql
- models/silver/swaps/orca/token_swap/silver__swaps_intermediate_orca_token_swap.yml
Refactor Orca token swaps using decoded instructions
- Will deprecate legacy models and update gold in separate PR
FR run on 2xl:
- `17:11:18  1 of 1 OK created sql incremental model silver.swaps_intermediate_orca_token_swap  [SUCCESS 1 in 589.98s]`
Inc run on medium:
- `17:52:17  Finished running 1 incremental model, 6 project hooks in 0 hours 0 minutes and 40.93 seconds (40.93s).`
tests passed:
```
17:53:38  Finished running 19 data tests, 6 project hooks in 0 hours 0 minutes and 36.09 seconds (36.09s).
17:53:39  Completed successfully
17:53:39  Done. PASS=19 WARN=0 ERROR=0 SKIP=0 TOTAL=19
```
> add updated orca token swap

- models/gold/defi/defi__fact_swaps.sql
- models/silver/protocols/marinade/silver__marinade_swaps.sql
- models/silver/swaps/orca/legacy/silver__swaps_intermediate_orca.sql
- models/silver/swaps/orca/legacy/silver__swaps_intermediate_orca_view.sql
- models/silver/swaps/silver__swaps.sql
- models/sources.yml
Add updated Orca swaps to gold and deprecate legacy
The new silver orca tables are large (~700m records), so letting the gold model run incrementally will take far too long. To update fact_swaps I will:
1. Delete the existing swaps using Orca programs
2. Run dev table to get it up-to-date and use insert statement into prod
> An 5632/update gold orca swaps

- models/gold/gov/gov__dim_epoch.sql
- models/gold/gov/gov__ez_staking_lp_actions.sql
- models/gold/gov/gov__ez_staking_lp_actions.yml
- models/gold/gov/gov__fact_block_production.sql
- models/gold/gov/gov__fact_gauges_creates.sql
- models/gold/gov/gov__fact_proposal_votes.sql
- models/gold/gov/gov__fact_proposal_votes.yml
- models/gold/gov/gov__fact_rewards_fee.sql
- models/gold/gov/gov__fact_rewards_fee.yml
- models/gold/gov/gov__fact_rewards_rent.sql
- models/gold/gov/gov__fact_rewards_staking.sql
- models/gold/gov/gov__fact_rewards_staking.yml
- models/gold/gov/gov__fact_rewards_voting.sql
- models/gold/gov/gov__fact_rewards_voting.yml
- models/gold/gov/gov__fact_votes_agg_block.sql
- models/gold/gov/gov__fact_votes_agg_block.yml
- models/silver/non_core/silver__staking_lp_actions_2.sql
- models/silver/rewards/silver__rewards_fee_2.sql
- models/silver/rewards/silver__rewards_staking_2.sql
- models/silver/rewards/silver__rewards_voting_2.sql
Convert view in GOV schema to tables. Also remove SO in silver tables
To update without downtime to users:
1. Add `_2` to models and run locally in prod
2. drop views, then rename `_2` tables -- ie. `ALTER TABLE solana.gov.fact_rewards_voting_2 RENAME TO solana.gov.fact_rewards_voting;`
3. Double-check grants
> gov gold table conversions

- models/gold/defi/defi__fact_swaps.sql
- models/gold/defi/defi__fact_swaps_jupiter_summary.sql
- models/silver/swaps/saber/silver__swaps_intermediate_saber.sql
- models/silver/swaps/saber/silver__swaps_intermediate_saber.yml
- models/silver/swaps/silver__swaps.sql
- models/silver/swaps/silver__swaps_view.sql
- models/sources.yml
Add saber dex tables and deprecate legacy fact_swaps table
- `silver.swaps_view` is relevant for jup2/3 programs that were last used 3+ years ago, so it is kept in the core model in case we FR
- will have to delete all saber programs using `SSwpkEEcbUqx4vtoEByFjSkhKdCT862DNVb52nZg1UZ` and `Crt7UoUR6QgrFrN7j8rmSQpUTNWNSitSwWvsWGf1qZ5t` from gold tables. Crt7... program was an internal aggregator that only leads to swaps using SSwpk...  so it can be completely removed.
runs
- saber incremental
`22:52:52  1 of 1 OK created sql incremental model silver.swaps_intermediate_saber ........ [SUCCESS 1051 in 21.14s]`
- saber - all tests passes
```
21:23:21  Finished running 17 data tests, 6 project hooks in 0 hours 0 minutes and 40.80 seconds (40.80s).
21:23:21  Completed successfully
21:23:21 …
```
> cureate saber; deprecate legacy swaps

- models/gold/defi/defi__fact_swaps.sql
- models/gold/defi/defi__fact_swaps.yml
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora_bonding.sql
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora_bonding.yml
Curate meteora bonding swaps
runs:
- FR of silver 
`19:09:37  Finished running 1 incremental model, 6 project hooks in 0 hours 1 minutes and 6.41 seconds (66.41s).`
- all tests passed
```
19:12:25  Finished running 13 data tests, 6 project hooks in 0 hours 0 minutes and 40.81 seconds (40.81s).
19:12:26  Completed successfully
19:12:26  Done. PASS=13 WARN=0 ERROR=0 SKIP=0 TOTAL=13
```
- successful run of fact_swaps after addition
`19:14:28  1 of 1 OK created sql incremental model defi.fact_swaps ........................ [SUCCESS 74258 in 21.37s]`
> add meteora bonding swaps

- models/streamline/core/realtime/streamline__block_txs_index.sql
Update model for backfilling tx_index
- Restart this workflow for transactions that ended up with null tx_index
- a temp dev table is created to store all the blocks that need to be rerun: `solana_dev.silver.backfill_tx_index_errors`
- dbt run --vars '{"UPDATE_UDFS_AND_SPS": True}' -s bronze__streamline_block_tx_index_backfill bronze__streamline_FR_block_tx_index_backfill -t dev
03:25:17  1 of 2 OK created sql view model bronze.streamline_FR_block_tx_index_backfill .. [SUCCESS 1 in 2.21s]
03:25:17  2 of 2 OK created sql view model bronze.streamline_block_tx_index_backfill ..... [SUCCESS 1 in 2.22s]
- dbt run -s silver__backfill_transactions_index -t dev --full-refresh
00:13:07  1 of 1 OK created sql incremental model silver.backfill_transactions_index ..... [SUCCESS 1 in 106.77s]
- dbt …
> update partition filter

- .github/workflows/dbt_test_tasks.yml
- models/github_actions/github_actions__current_task_status.yml
Tests now passing after filtering out snapshot stake accounts job (which runs on a custom trigger):
```
1 of 2 PASS dbt_expectations_expect_column_values_to_be_in_set_github_actions__current_task_status_PIPELINE_ACTIVE__True  [PASS in 15.73s]
2 of 2 PASS dbt_expectations_expect_column_values_to_be_in_set_github_actions__current_task_status_SUCCESSES__2  [PASS in 15.73s]
```
> exclude stake snapshot; add alerting

- .github/workflows/dbt_run_daily.yml
- models/gold/gov/gov__fact_gov_actions.sql
- models/silver/governance/silver__gov_actions_saber.sql
- models/silver/governance/silver__gov_actions_saber_view.sql
- models/silver/protocols/marinade/silver__marinade_swaps.sql
- models/silver/swaps/generic/silver__swaps_intermediate_generic.sql
- models/silver/swaps/generic/silver__swaps_intermediate_generic_view.sql
- models/silver/swaps/silver__swaps.sql
- models/sources.yml
Cleanup unused models
- remove old stake accts pipeline from daily job
- generic swaps table is deprecated as it was replaced by other models, specifically the new saber table
- deprecate gov_actions_saber as no new records in last month
> deprecate unused models

- models/gold/defi/defi__fact_swaps.sql
- models/silver/swaps/meteora/silver__swaps_intermediate_meteora_bonding.sql
Add DAMM v2 program to swaps
- just added the program to the `meteora_bonding` model because the logic is very similar, and then making sure its properly identified in fact_swaps
- Incremental run successful:
```
19:07:35  1 of 2 OK created sql incremental model silver.swaps_intermediate_meteora_bonding  [SUCCESS 18659 in 32.41s]
19:08:16  2 of 2 OK created sql incremental model defi.fact_swaps ........................ [SUCCESS 15586841 in 41.10s]
```
- tests passed:
```
19:21:36  Finished running 16 data tests, 6 project hooks in 0 hours 0 minutes and 52.64 seconds (52.64s).
19:21:37  Completed successfully
19:21:37  Done. PASS=16 WARN=0 ERROR=0 SKIP=0 TOTAL=16
```
> add damm meteora program

- models/silver/non_core/silver__mint_actions.sql
- models/silver/non_core/silver__mint_actions.yml
`Mint_actions` was missing some tx's due to incremental logic and after update on 25-04-01 to use `events_inner`
- set `max(_inserted_timestamp)` for consistent filter
- use merge incremental
- improved unique id
- add cols for better tracking
> update mint actions logic

- .github/workflows/dbt_run_incremental_non_core_hourly.yml
add `incremental_non_core_hourly` job to same concurrency as `incremental_intermediate`
- From analysis, the avg overlap is 3-4 minutes for `incremental_intermediate` running at minute `46` and `non_core_hourly` running at minute `1`. If the 'incremental_non_core_hourly' run is then pushed back those few minutes it shouldn't affect other runs.
- May be a temp change as we monitor
> add non_core_hourly job concurrency

- models/gold/marinade/marinade__ez_liquidity_pool_actions.sql
- models/gold/marinade/marinade__meteora_dlmm_pivot.sql
- models/gold/marinade/marinade__meteora_multi_pivot.sql
- models/gold/marinade/marinade__meteora_pivot.sql
- models/silver/liquidity_pool/silver__liquidity_pool_actions_meteora.sql
- models/silver/liquidity_pool/silver__liquidity_pool_actions_meteora_dlmm.sql
- models/silver/liquidity_pool/silver__liquidity_pool_actions_meteora_multi.sql
- models/silver/parser/silver__decoded_instructions_combined.yml
- models/silver/protocols/marinade/silver__marinade_swaps.sql
Update `marinade` tables
- For ez_liquidity_pool actions, use newer `_2` meteora tables. The `_pivot` tables were created because the existing meteora tables werent in the standard format as other lp tables. The `_pivot` tables have been disabled, as well as the old `silver` tables.
- For `marinade_swaps`, add in swap protocols that were missing.
> An 6397/marinade update

- models/descriptions/__overview__.md
- models/descriptions/tables/ez_signers.md
- models/descriptions/tables/ez_transfers.md
- models/descriptions/tables/fact_decoded_instructions.md
- models/descriptions/tables/fact_events.md
- models/descriptions/tables/fact_events_inner.md
- models/descriptions/tables/fact_sol_balances.md
- models/descriptions/tables/fact_stake_pool_actions.md
- models/descriptions/tables/fact_token_account_owners.md
- models/descriptions/tables/fact_token_balances.md
- models/descriptions/tables/fact_token_burn_actions.md
- models/descriptions/tables/fact_token_mint_actions.md
- models/descriptions/tables/fact_transactions.md
- models/descriptions/tables/fact_transfers.md
- models/gold/core/core__ez_transfers.yml
- Updated all table descriptions to reference `ez_transfers` instead of `fact_transfers` for transfer analytics
- Created comprehensive `ez_transfers.md` documentation following project standards to replace the old descriptions
- Enhanced `fact_transactions` documentation to strongly emphasize using curated tables over raw transaction data
> update desc for ez_transfers; update transactions

- .github/workflows/dbt_test_weekly.yml
- models/silver/core/silver__votes.sql
Delete records older then 6 months in `silver.votes`
- use pre_hook with var, which runs weekly (added to test_weekly job to avoid adding more workflows)
- Votes data goes largely unused, as only recent data is necessary for the gold votes_agg table and for observability purposes. The decision to only keep 6 months of data was due to the costs of storage ($7k+ yearly savings from removing the old data), and there has been little to no interest from users to have the 'raw' vote data available.
> delete past 6months of vote data
